### ISSUE TITLE
Error: Bad FEType.family= 41 on using pbc's with LAGRANGE_VEC

### ISSUE THREAD

**Issue by ahzeeshan** [idaholab/moose#13030] opened 2019-03-08 21:17 UTC
## Rationale
Moose gives an error when using periodic boundary conditions for a scalar in a file which has a LAGRANGE_VEC variable.

## Description
The minimal example is here:
https://gist.github.com/ahzeeshan/0e132d487d960953c90e69d082896826
The file CSV.i (containing periodic boundary conditions for the scalar v) gives the error Bad FEType.family= 41 when run with ./moose_test-opt executable in the moose/test/ directory whereas the file CSV_working.i runs fine.

## Impact
Enable the use of periodic boundary conditions for scalars in a file containing vector variables.

**Comment by jiangwen84** [comment] 2020-01-15 20:05
https://groups.google.com/forum/#!topic/moose-users/un-XNHAgGuw

I modified one regression test  (moose/test/tests/kernels/vector_fe/lagrange_vec.i) by adding an adaptivity block, see below

[Adaptivity]
  steps = 1
  marker = box
  max_h_level = 2
  initial_steps = 2
  [./Markers]
    [./box]
      bottom_left = '0.3 0.3 0'
      inside = refine
      top_right = '0.6 0.6 0'
      outside = do_nothing
      type = BoxMarker
    [../]
  [../]
[]

I ran the input and got the error messages

ERROR: Bad FEType.family= 41
Stack frames: 23
0: 0   libmesh_opt.0.dylib                 0x000000010d7caede libMesh::print_trace(std::__1::basic_ostream<char, std::__1::char_traits<char> >&) + 1198
1: 1   libmesh_opt.0.dylib                 0x000000010d7c6eae libMesh::MacroFunctions::report_error(char const*, int, char const*, char const*) + 270
2: 2   libmesh_opt.0.dylib                 0x000000010d8782a3 libMesh::FEGenericBase<double>::build(unsigned int, libMesh::FEType const&) + 3027
3: 3   libmesh_opt.0.dylib                 0x000000010dd4d90d libMesh::FEGenericBase<double>* libMesh::FEMContext::build_new_fe<double>(libMesh::FEGenericBase<double> const*, libMesh::Point const&, double) const + 189
4: 4   libmesh_opt.0.dylib                 0x000000010dd4d78e void libMesh::FEMContext::point_value<double>(unsigned int, libMesh::Point const&, double&, double) const + 78
5: 5   libmesh_opt.0.dylib                 0x000000010ddab5ed libMesh::GenericProjector<libMesh::OldSolutionValue<double, &(void libMesh::FEMContext::point_value<double>(unsigned int, libMesh::Point const&, double&, double) const)>, libMesh::OldSolutionValue<libMesh::VectorValue<double>, &(void libMesh::FEMContext::point_gradient<libMesh::VectorValue<double> >(unsigned int, libMesh::Point const&, double&, double) const)>, double, libMesh::VectorSetAction<double> >::SubProjector::construct_projection(std::__1::vector<unsigned int, std::__1::allocator<unsigned int> > const&, std::__1::vector<unsigned int, std::__1::allocator<unsigned int> > const&, unsigned int, libMesh::Node const*, libMesh::FEGenericBase<double> const&) + 1229
6: 6   libmesh_opt.0.dylib                 0x000000010ddac036 libMesh::GenericProjector<libMesh::OldSolutionValue<double, &(void libMesh::FEMContext::point_value<double>(unsigned int, libMesh::Point const&, double&, double) const)>, libMesh::OldSolutionValue<libMesh::VectorValue<double>, &(void libMesh::FEMContext::point_gradient<libMesh::VectorValue<double> >(unsigned int, libMesh::Point const&, double&, double) const)>, double, libMesh::VectorSetAction<double> >::ProjectSides::operator()(libMesh::StoredRange<std::__1::__wrap_iter<std::__1::pair<libMesh::Node const*, std::__1::tuple<libMesh::Elem const*, unsigned short, std::__1::set<unsigned int, std::__1::less<unsigned int>, std::__1::allocator<unsigned int> > > > const*>, std::__1::pair<libMesh::Node const*, std::__1::tuple<libMesh::Elem const*, unsigned short, std::__1::set<unsigned int, std::__1::less<unsigned int>, std::__1::allocator<unsigned int> > > > > const&) + 1222
7: 7   libmesh_opt.0.dylib                 0x000000010dd9f1cb void libMesh::Threads::parallel_reduce<libMesh::StoredRange<std::__1::__wrap_iter<std::__1::pair<libMesh::Node const*, std::__1::tuple<libMesh::Elem const*, unsigned short, std::__1::set<unsigned int, std::__1::less<unsigned int>, std::__1::allocator<unsigned int> > > > const*>, std::__1::pair<libMesh::Node const*, std::__1::tuple<libMesh::Elem const*, unsigned short, std::__1::set<unsigned int, std::__1::less<unsigned int>, std::__1::allocator<unsigned int> > > > >, libMesh::GenericProjector<libMesh::OldSolutionValue<double, &(void libMesh::FEMContext::point_value<double>(unsigned int, libMesh::Point const&, double&, double) const)>, libMesh::OldSolutionValue<libMesh::VectorValue<double>, &(void libMesh::FEMContext::point_gradient<libMesh::VectorValue<double> >(unsigned int, libMesh::Point const&, double&, double) const)>, double, libMesh::VectorSetAction<double> >::ProjectSides>(double const&, libMesh::GenericProjector<libMesh::OldSolutionValue<double, &(void libMesh::FEMContext::point_value<double>(unsigned int, libMesh::Point const&, double&, double) const)>, libMesh::OldSolutionValue<libMesh::VectorValue<double>, &(void libMesh::FEMContext::point_gradient<libMesh::VectorValue<double> >(unsigned int, libMesh::Point const&, double&, double) const)>, double, libMesh::VectorSetAction<double> >::ProjectSides&) + 59
8: 8   libmesh_opt.0.dylib                 0x000000010dd920dd libMesh::GenericProjector<libMesh::OldSolutionValue<double, &(void libMesh::FEMContext::point_value<double>(unsigned int, libMesh::Point const&, double&, double) const)>, libMesh::OldSolutionValue<libMesh::VectorValue<double>, &(void libMesh::FEMContext::point_gradient<libMesh::VectorValue<double> >(unsigned int, libMesh::Point const&, double&, double) const)>, double, libMesh::VectorSetAction<double> >::project(libMesh::StoredRange<libMesh::MeshBase::const_element_iterator, libMesh::Elem const*> const&) + 5245
9: 9   libmesh_opt.0.dylib                 0x000000010dd8f78c libMesh::System::project_vector(libMesh::NumericVector<double> const&, libMesh::NumericVector<double>&, int) const + 2044
10: 10  libmesh_opt.0.dylib                 0x000000010dd8ef3f libMesh::System::project_vector(libMesh::NumericVector<double>&, int) const + 47
11: 11  libmesh_opt.0.dylib                 0x000000010dd6c6b7 libMesh::System::restrict_vectors() + 183
12: 12  libmesh_opt.0.dylib                 0x000000010dd3e4e9 libMesh::EquationSystems::reinit_solutions() + 2233
13: 13  libmesh_opt.0.dylib                 0x000000010dd3dc1e libMesh::EquationSystems::reinit() + 14
14: 14  libmoose-opt.0.dylib                0x000000010ac32538 FEProblemBase::meshChangedHelper(bool) + 360
15: 15  libmoose-opt.0.dylib                0x000000010ac57aa9 FEProblemBase::meshChanged() + 41
16: 16  libmoose-opt.0.dylib                0x000000010ac573b8 FEProblemBase::initialAdaptMesh() + 232
17: 17  libmoose-opt.0.dylib                0x000000010ac2d274 FEProblemBase::initialSetup() + 3364
18: 18  libmoose-opt.0.dylib                0x000000010b1f4a5b MooseApp::executeExecutioner() + 75
19: 19  libmoose-opt.0.dylib                0x000000010b1f55a3 MooseApp::run() + 227
20: 20  combined-opt                        0x000000010a86db63 main + 163
21: 21  libdyld.dylib                       0x00007fff715ae3d5 start + 1
22: 22  ???                                 0x0000000000000003 0x0 + 3

**Comment by jiangwen84** [comment] 2020-01-15 20:58
@lindsayad do you have any idea how this should be fixed in libMesh?

**Comment by lindsayad** [comment] 2020-01-15 21:06
I’m at Oak Ridge right now and I spilled coffee on my laptop this morning... I can investigate possibly tomorrow night or early next week. Is this something that’s high priority for you?

**Comment by jiangwen84** [comment] 2020-01-15 21:12
sorry to hear that :-)  

I am using NS module and looks like all the AD staff uses vector variables now. It is not urgent but it will be nice to have it fixed. Next week is totally fine. Thanks.

**Comment by lindsayad** [comment] 2020-01-15 21:25
Ah yes. I’m glad you’re using the NS module! I’m definitely motivated to get this working for you then :-)

**Comment by jiangwen84** [comment] 2020-01-27 20:05
@lindsayad did you have any time to look at it yet? I hope it won't take you too much time :-)

**Comment by lindsayad** [comment] 2020-01-27 22:12
I am going to look at it now. I was working on #14626 first

**Closed** 2020-02-06 16:58 UTC
Labels: C: MOOSE, P: normal, T: task
