### ISSUE TITLE
exodus output bug following coarsening and recovery?

### ISSUE THREAD

**Issue by jessecarterMOOSE** [idaholab/moose#8890] opened 2017-04-08 03:14 UTC
### Description of the enhancement or error report

Exodus output shows some weird artifacts when mesh adaptivity is used followed by a recover. The solution is not affected, just the output.
An example looks like:
![artifacts](https://cloud.githubusercontent.com/assets/12945054/24825176/760287aa-1be7-11e7-94f6-1851273e4599.png)

### Rationale for the enhancement or information for reproducing the error

In some cases, doing some small amount of mesh coarsening, but not a lot, followed by a recover, produces the artifacts. I will submit a PR showing this.

### Identified impact
(i.e. Internal object changes, limited interface changes, public API change, or a list of specific applications impacted)
Less bugs.

**Comment by jessecarterMOOSE** [comment] 2017-08-02 13:50
BTW this appears to still be an issue. 

You can see it by checking out my branch [jessecarterMOOSE:demo_exodus_bug](https://github.com/jessecarterMOOSE/moose/tree/demo_exodus_bug) and running 
`./run_tests --recover two_circle_marker`

There is also a possibly related distributed mesh bug that gives a segfault:
`./run_tests --distributed-mesh two_circle_marker`

Some discussion on the linked PR.

Tagging @permcody @roystgnr

**Comment by permcody** [comment] 2017-08-02 14:25
Acknowledged - I'll see if I can take a look at this in our "tiger team" meeting in a few weeks.

**Comment by jessecarterMOOSE** [comment] 2017-08-02 14:32
Awesome. Thanks and good luck! :+1:

**Comment by roystgnr** [comment] 2017-08-02 16:56
Damn.  I was hoping to have this fixed *before* the Tiger Team, but then "recovery bugs" got preempted by "DistributedMesh bugs" which got preempted by "parallel ReplicatedMesh bugs"...

I think I've now fixed all the serious test failures with parallel ReplicatedMesh (which is passing everything up to -np 12, and is only failing "tiny mesh with so many processors that some don't own a single node" tests afterward).  There's still a couple serious MOOSE+DistributedMesh bugs... but at least one of those looks like a restart bug, which might overlap with this one.  Let me get a PR in for one of the non-serious test failures and then I'll try out your branch; thanks.

**Comment by roystgnr** [comment] 2017-08-02 20:29
Is there actually a recovery going on here?  It looks as if two_circle_marker_gaussian_ic.i just initializes from a ParsedFunction then runs for a half dozen time steps, doing a refinement/coarsening step after the first couple.

Anyway, I can replicate the problem.  two_circle_marker_gaussian_ic_out.e looks just fine in the eyeball norm.  But what's baffling: two_circle_marker_gaussian_ic_out.e-s002 in paraview looks perfectly fine at time 0, t=0.3, but then scrambles at time 1, t=0.4.  If there was just some simple misindexing going on I would have expected it to be consistent at every step in the new file.

**Comment by roystgnr** [comment] 2017-08-02 20:30
Ah, wait, never mind; --recover comes in via the command line.

**Comment by roystgnr** [comment] 2017-08-02 20:32
Presumably that's also why the failure occurs at t=0.4?  The t=0.3 output is pre-recovery, and the t=0.4 output is post-?

**Comment by permcody** [comment] 2017-08-02 20:36
Yes, exactly. That file should have been output before the first half of the simulation terminated. The recovery doesn't need to output the "initial condition" since it's already there so it starts with the next solved step.

**Comment by roystgnr** [comment] 2017-08-04 17:19
Okay; I've got a fix for the 1 processor case at least.  Just need to try out in parallel and distributed and then I'll put together a PR before I'm done for the day.

**Comment by roystgnr** [comment] 2017-08-04 17:55
I've added some more debugging support in the course of figuring out the problem here, so I'll put in a second PR for that soon too.

I'm afraid my fix does *not* get your test working with --distributed-mesh, and I could swear that the issue I'm seeing now looks different from the one [I described before](https://github.com/idaholab/moose/pull/8891#issuecomment-308002408), so there may be a third and fourth PR in the more distant future...

**Closed** 2017-08-07 16:45 UTC
Labels: C: MOOSE, P: critical, T: defect

**Comment by roystgnr** [comment] 2017-08-07 17:10
The --distributed-mesh problems were independent of the problem described visually above, so I think we can just class them in #8410 and leave this closed, assuming that the fix in #9608 worked for @jessecarterMOOSE too.

And in that case, could we get this test added to the MOOSE test suite permanently?  It covered multiple bugs, in MOOSE and in libMesh, at least one of which wasn't getting triggered by the existing test coverage.

**Comment by roystgnr** [comment] 2017-08-07 17:19
It also triggers a failure I haven't figured out yet, in fact...  My runs with --distributed-mesh (using my upcoming libMesh DistributedMesh CheckpointIO fixes), with or without recovery, work on 1 through 6 processors but then fail on 7, this time with exodiff errors on the order of 1e-4, which looks too small to be a logic error but way too large to be roundoff or solver error.

**Comment by jessecarterMOOSE** [comment] 2017-08-08 00:21
Works for me @roystgnr, using ReplicatedMesh at least. That's a start! Thanks! :+1: 

@permcody Should I re-open my PR with the two-circle marker test that spawned this whole endeavor? I know you're not keen on adding more test objects, but it seems it adds more coverage.

**Comment by permcody** [comment] 2017-08-08 13:58
I'm OK with that.

**Comment by roystgnr** [comment] 2017-08-08 14:22
Thanks!

I've had a love-hate relationship with AMR tests in MOOSE, because although it's a very critical feature to cover, all it takes is a little symmetry in the problem and suddenly you have a reproduceability nightmare: one run says that element A has an error of 0.5 and B has 0.5+1e-9, so B gets refined; the next says A has 0.5 and B has 0.5-1e-9, so A gets refined, and suddenly exodiff is guaranteed to fail.  I think I've got one or two PRs in MOOSE history that are nothing more than "I give up, let's just run fewer steps so this thing will actually give us a consistent refinement pattern through all of them".

In libMesh and GRINS we instead give up on element-by-element regression tests and just compare QoI values or Hilbert norms.  But this test here is a fantastic alternative: use a marker class with defined constant behavior instead of an error indicator with discontinuous behavior, and you get all the AMR you want with exactly the same mesh every time!  The "love-hate" is now pure love.

I know there are other marker classes already in MOOSE, and we might configure one of them to similar effect?  But I'd rather add a new class that *definitely* covers old bugs instead of reusing a class that *probably* would cover them.
