### ISSUE TITLE
mooseWarning print out warning messages on all processors

### ISSUE THREAD

**Issue by YaqiWang** [idaholab/moose#6280] opened 2016-02-08 19:24 UTC
with MPI. If the number of processors is large, the screen output is messy. I suggest to only print out message on the master processor by default.

**Comment by permcody** [comment] 2016-02-08 23:33
This has come up before in #4668.

Right now `mooseWarning()` and `mooseError()` both print to stderr instead of stdout. There are some good reasons for this, but there are also some down sides. In the case where only one processor hits a warning you may not see that output, however in many cases, all processors hit that path and you see it all. I'm not sure if we should "fix" this or not. It's been debated before with enough dissent that nothing has changed.

An easy way to handle this is to pipe your stderr to a separate stream so you don't see it in your console output. If you have a problem with your run, you can also open the stderr stream to look at the warnings.

Either way, I'll close this ticket since the issue is captured in the one referenced above.

**Closed by permcody** 2016-02-08 23:33 UTC

**Comment by YaqiWang** [comment] 2016-02-08 23:45
I see. If the developer are sure the warning will be hit by all processors always, he can protect the warning by if processor_id is equal to master.

**Comment by permcody** [comment] 2016-02-08 23:53
That's a reasonable workaround. I think this is a good debate to have.
