### ISSUE TITLE
"run_as" app parameter

### ISSUE THREAD

**Issue by permcody** [idaholab/moose#5063] opened 2015-05-14 21:09 UTC
There has been some interest in allowing composite applications to "run_as" different applications. This was useful in the early multiapp days but is slightly less useful now with the addition of all of the dynamic loading in MOOSE. There are still cases where it might make sense but It's a non-trivial task since it will end up changing main.C in each application:

At the very least we'll need a static method that creates a GetPot Parser to read the input file for the chosen "run_as" parameter. This method would then report the selected value back to the main application where the Application is dynamically created by name.

For right now, I suggest that most people use the dynamic registration to achieve a similar effect. Please tag the moose team on this ticket if you have a more urgent use case.

**Comment by friedmud** [comment] 2015-06-12 14:59
@permcody I think this is a duplicate of #3757 can you confirm?

#3757 has a little more design in it... so maybe we should close this in favor of that one?

**Comment by permcody** [comment] 2015-06-12 15:25
It is a duplicate, but note my comments. I was going to implement this a
few weeks back when I realized it would force a change in main. I decided
it was low priority due to the fact that we can effectively accomplish the
same behavior with dynamic application registration with a few caveats.

**Comment by permcody** [comment] 2015-06-12 15:39
Actually I guess I don't have to modify main. Since there's a fair amount
of work in parsing the file to even figure out that a run_app parameter
exists. We could construct the necessary objects to get that far including
the default app and then construct the run_as app later and cleaning up or
transferring objects to the new app and running...

**Comment by lindsayad** [comment] 2024-01-16 05:22
This functionality was enabled with the completion of #20062 and we will be adding the capability to do this from an input file in #23741 so I am going to close this

**Closed by lindsayad** 2024-01-16 05:22 UTC
Labels: C: Framework, P: minor, T: task
