### ISSUE TITLE
PNG unit tests run regardless of MOOSE_HAVE_LIBPNG

### ISSUE THREAD

**Issue by roystgnr** [idaholab/moose#14179] opened 2019-10-16 19:33 UTC
## Bug Description
When MOOSE is built on a system without libpng development files, then PNGOutput is not compiled, but outputs/png.image_tests unit tests get run anyway, and fail at runtime.

## Steps to Reproduce
Build MOOSE framework and tests on a system without ```pkg-config --libs libpng```, then ```./run_tests``` in the test directory.

## Impact
Minor annoyance.

**Comment by permcody** [comment] 2019-10-17 22:50
Duplicate of #14012. I'll bump priority a bit. Should be a pretty simple fix if we write it out in our MooseConfig file.

**Closed** 2019-10-17 22:50 UTC
Labels: C: TestHarness, P: minor, T: defect
