### ISSUE TITLE
Cyclic dependency is too strict (execute_on flags not respected)

### ISSUE THREAD

**Issue by WilkAndy** [idaholab/moose#7626] opened 2016-08-25 09:22 UTC
### Description of the enhancement or error report

I think the Cyclic Dependency check is too harsh.  If I'm wrong, could someone tell me another way of doing what i need to do.

### Rationale for the enhancement or information for reproducing the error

These are the blocks in my input file that cause problems:

```
  [./encoder_auxk]
    type = PorousFlowVariableSwitchEncoder
    porepressure = porepressure
    saturation = saturation
    variable = encoder
    execute_on = 'timestep_begin'
  [../]
  [./updater_pp]
    type = PorousFlowVariableSwitchUpdater
    p_or_s_variable = thevar
    encoder_auxvar = encoder
    m = 0.8
    al = 1E-5
    updating_porepressure = true
    variable = porepressure
    execute_on = 'nonlinear timestep_end'
  [../]
```

Notice the different "execute_on" times.

This is MOOSE's error:

```
*** ERROR ***
Cyclic dependency detected in object ordering:
encoder_auxk -> updater_pp
updater_pp -> encoder_auxk
```

### Identified impact
(i.e. Internal object changes, limited interface changes, public API change, or a list of specific applications impacted)

**Comment by permcody** [comment] 2016-08-25 13:29
That looks like a bug to me.

**Comment by permcody** [comment] 2016-09-06 20:30
Hmm, I was going to take a look at this but I don't think I have all the information I need since these objects aren't checked in. Is the top object an AuxKernel and the bottom object a PostProcessor? Is there any linkage that I can't see here?

**Comment by WilkAndy** [comment] 2016-09-06 22:41
Sorry those things aren't checked in - they were temporary tries at something i was working on.  I've since moved away from that scheme, so don't really need this fixed right now, but of course the bug still exists.  They were both AuxKernels (despite the crazy naming scheme!).

**Comment by permcody** [comment] 2016-09-07 14:48
Confirmed. It appears that we do not respect the `execute_on` flags at all. When sorting on dependencies. This is more or less baked into the warehouse design and should be fixed. Ping @aeslaughter.

**Closed** 2016-09-07 22:13 UTC
Labels: C: MOOSE, P: normal, T: defect
