### ISSUE TITLE
Issue with environment creation

### ISSUE THREAD

**Issue by bshgithub** [idaholab/moose#28498] opened 2024-08-29 17:57 UTC
Hi
I'm trying to  install mini forge (in order to install moose). however im getting these errors during the make-j6 tests:

```pre
misc/check_error.missing_function_file_test ....................... [FINISHED] FAILED (EXPECTED ERROR MISSING)
misc/check_error.function_file_test16 ........................................ FAILED (EXPECTED ERROR MISSING)
misc/check_error.check_syntax_no_input ....................................... FAILED (EXPECTED ERROR MISSING)
misc/check_error.missing_required_param_in_kernel_test ....................... FAILED (EXPECTED ERROR MISSING)
misc/check_error.dg_kernel_with_aux_var ........................... [FINISHED] FAILED (EXPECTED ERROR MISSING)
misc/check_error.bad_kernel_test ............................................. FAILED (EXPECTED ERROR MISSING)
misc/check_error.subdomain_restricted_auxkernel_test ......................... FAILED (EXPECTED ERROR MISSING)
misc/check_error.check_git_lfs_pointer ....................................... FAILED (EXPECTED ERROR MISSING)
misc/check_error.dynamic_check_name_block_test ............................... FAILED (EXPECTED ERROR MISSING)
misc/check_error.coupling_itself_ad .......................................... FAILED (EXPECTED ERROR MISSING)
misc/check_error.wrong_input_switch ......................................... FAILED (EXPECTED OUTPUT MISSING)
misc/check_error.function_file_test7 ......................................... FAILED (EXPECTED ERROR MISSING)
misc/check_error.function_file_test17 ........................................ FAILED (EXPECTED ERROR MISSING)
misc/check_error.interface_kernel_with_aux_var ............................... FAILED (EXPECTED ERROR MISSING)
misc/check_error.multiple_time_int_check ..................................... FAILED (EXPECTED ERROR MISSING)
misc/check_error.missing_function_test ....................................... FAILED (EXPECTED ERROR MISSING)
misc/check_error.bad_kernel_var_test ......................................... FAILED (EXPECTED ERROR MISSING)
misc/check_error.missing_var_parameter_test .................................. FAILED (EXPECTED ERROR MISSING)
misc/check_error.check_git_lfs_pointer_fmg ................................... FAILED (EXPECTED ERROR MISSING)
misc/check_error.steady_no_converge ......................................... FAILED (EXPECTED OUTPUT MISSING)
misc/check_error.subdomain_restricted_kernel_test ............................ FAILED (EXPECTED ERROR MISSING)
misc/check_error.dynamic_check_name_boundary_mismatch_test ................... FAILED (EXPECTED ERROR MISSING)
misc/check_error.missing_input ............................................... FAILED (EXPECTED ERROR MISSING)
misc/check_error.function_file_test8 ......................................... FAILED (EXPECTED ERROR MISSING)
misc/check_error.incomplete_kernel_block_coverage_test ....................... FAILED (EXPECTED ERROR MISSING)
misc/check_error.ics_missing_variable ........................................ FAILED (EXPECTED ERROR MISSING)
misc/check_error.kernel_with_empty_var ....................................... FAILED (EXPECTED ERROR MISSING)
misc/check_error.bad_bc_var_test ............................................. FAILED (EXPECTED ERROR MISSING)
misc/check_error.missing_material_prop_test .................................. FAILED (EXPECTED ERROR MISSING)
misc/check_error.calling_wrong_feproblem_method .............................. FAILED (EXPECTED ERROR MISSING)
misc/check_error.bad_material_test ........................................... FAILED (EXPECTED ERROR MISSING)
misc/check_error.missing_required_coupled_test ............................... FAILED (EXPECTED ERROR MISSING)
misc/check_error.unused_param_test ........................................... FAILED (EXPECTED ERROR MISSING)
misc/check_error.dynamic_check_name_boundary_test ............................ FAILED (EXPECTED ERROR MISSING)
misc/check_error.range_check_param ........................................... FAILED (EXPECTED ERROR MISSING)
misc/check_error.kernel_with_aux_var ......................................... FAILED (EXPECTED ERROR MISSING)
misc/check_error.coupling_itself ............................................. FAILED (EXPECTED ERROR MISSING)
misc/check_error.vector_kernel_with_standard_var ............................. FAILED (EXPECTED ERROR MISSING)
misc/check_error.ic_bnd_for_non_nodal ........................................ FAILED (EXPECTED ERROR MISSING)
misc/check_error.function_file_test9 ......................................... FAILED (EXPECTED ERROR MISSING)
misc/check_error.incomplete_kernel_variable_coverage_test .................... FAILED (EXPECTED ERROR MISSING)
misc/check_error.missing_material_prop_test2 ................................. FAILED (EXPECTED ERROR MISSING)
misc/check_error.wrong_displacement_order .................................... FAILED (EXPECTED ERROR MISSING)
misc/check_error.checked_pointer_param_test .................................. FAILED (EXPECTED ERROR MISSING)
misc/check_error.bad_parsed_function_vars_test ............................... FAILED (EXPECTED ERROR MISSING)
misc/check_error.multi_precond_test .......................................... FAILED (EXPECTED ERROR MISSING)
misc/check_error.unused_param_test_cli ....................................... FAILED (EXPECTED ERROR MISSING)
misc/check_error.bc_with_aux_var ............................................. FAILED (EXPECTED ERROR MISSING)
misc/check_error.function_file_test10 ........................................ FAILED (EXPECTED ERROR MISSING)
misc/check_error.linear_interp_material_check ................................ FAILED (EXPECTED ERROR MISSING)
--------------------------------------------------------------------------------------------------------------
Ran 50 tests in 56.1 seconds. Average test time 3.0 seconds, maximum test time 28.2 seconds.
0 passed, 92 skipped, 0 pending, 50 FAILED
MAX FAILURES REACHED 
```

if anyone could help that would be great(I', on a 16 inch 2019 Mac (intel processor).
Thanks!

**Comment by bshgithub** [comment] 2024-08-31 19:04
Yes, I'm away atm, but I'll work on it when I get back.

Thanks

**Comment by bshgithub** [comment] 2024-09-03 18:45
Hi,
So I have tried the solutions on:https://mooseframework.inl.gov/help/troubleshooting.html, and I am still getting errors.
(moose) bareaseeley-harris@Bareas-MacBook-Pro-2 test % cd moose/test
make -j 8
./run_tests -i always_ok -p 2
cd: no such file or directory: moose/test
cd moose/test
make -j 8
./run_tests -i always_ok -p 2
tests/test_harness.always_ok ......................................................................... RUNNING
tests/test_harness.always_ok: Working Directory: /Users/bareaseeley-harris/projects/moose/test/tests/test_harness
tests/test_harness.always_ok: Running command: mpiexec -n 2 /Users/bareaseeley-harris/projects/moose/test/moose_test-opt -i good.i --error --error-override --libtorch-device cpu
tests/test_harness.always_ok: 
tests/test_harness.always_ok: ===================================================================================
tests/test_harness.always_ok: =   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
tests/test_harness.always_ok: =   PID 40316 RUNNING AT Bareas-MacBook-Pro-2.local
tests/test_harness.always_ok: =   EXIT CODE: 4
tests/test_harness.always_ok: =   CLEANING UP REMAINING PROCESSES
tests/test_harness.always_ok: =   YOU CAN IGNORE THE BELOW CLEANUP MESSAGES
tests/test_harness.always_ok: ===================================================================================
tests/test_harness.always_ok: YOUR APPLICATION TERMINATED WITH THE EXIT STRING: Illegal instruction: 4 (signal 4)
tests/test_harness.always_ok: This typically refers to a problem with your application.
tests/test_harness.always_ok: Please see the FAQ page for debugging suggestions
tests/test_harness.always_ok: 
tests/test_harness.always_ok: 
tests/test_harness.always_ok: Exit Code: 4
tests/test_harness.always_ok: ################################################################################
tests/test_harness.always_ok: Tester failed, reason: CRASH
tests/test_harness.always_ok: 
tests/test_harness.always_ok ............................................. [OVERSIZED,FINISHED] FAILED (CRASH)


Final Test Results:
--------------------------------------------------------------------------------------------------------------
tests/test_harness.always_ok ............................................. [OVERSIZED,FINISHED] FAILED (CRASH)
--------------------------------------------------------------------------------------------------------------
Ran 1 tests in 17.5 seconds. Average test time 17.1 seconds, maximum test time 17.1 seconds.
0 passed, 0 skipped, 0 pending, 1 FAILED
(moose) bareaseeley-harris@Bareas-MacBook-Pro-2 test %

**Comment by milljm** [comment] 2024-09-03 19:59
Ah. You're now hitting a known issue as described in several discussions.

Unfortunately there is not much that can be done at the moment. Several discussions on this same error have been linked to the original discussion: https://github.com/idaholab/moose/discussions/28461#discussioncomment-10454037 with a "work around". However, that work around is quickly becoming unfeasible the further we march forward (see linked discussion for details).

Closing this issue, as it is now related/duplicate of: #28484

**Closed by milljm** 2024-09-03 19:59 UTC

**Comment by GiudGiud** [comment] 2024-09-07 13:11
The fix is now in all branches of moose. If you update with 
```
conda install moose-dev=2024.08.30 mpich
```
you should get working binaries
