### ISSUE TITLE
MultiAppMeshFunctionTransfer and MultiAppNearestNodeTransfer do not work properly with CONSTANT MONOMIAL

### ISSUE THREAD

**Issue by vincentlaboure** [idaholab/moose#12245] opened 2018-10-03 22:07 UTC
## Rationale

Two defects are being reported in this issue. It looks like:
1) `MultiAppMeshFunctionTransfer` does not work appropriately with CONSTANT MONOMIAL if the master mesh is more refined than the subapp mesh (even if the latter is strictly included in the former). More specifically, it seems that the transfer is not conservative which is surprising since the projection should be pretty straightforward.   

2) `MultiAppNearestNodeTransfer` does not work appropriately with CONSTANT MONOMIAL (regardless of the refinement). In that case, the transferred field is zero everywhere... Yet, the source code seems to cover the `!is_nodal` case.

## Description

To reproduce the errors:

1) Go [here](https://github.com/vincentlaboure/moose/tree/multiapp_transfer_problems/test/tests/transfers/transfer_pb) and run the master file (may need to change `MultiApps/sub_app/app_type`). The subapp postprocessor `pwr_density_avg` returns 4.75 while it should be 5 (not conservative). If `Mesh/uniform_refine` is set to 1, the expected value is obtained.

2) Run the same input files as before but change `Transfers/to_sub_power_density/type` to `MultiAppNearestNodeTransfer`. Both subapp postprocessors (`power_density_max` and `pwr_density_avg`) return zero. The same result is obtained regarless of `Mesh/uniform_refine`.

## Impact

Both of these are problematic because some multiphysics applications require to transfer CONSTANT MONOMIAL variables.

**Comment by friedmud** [comment] 2018-10-04 01:43
1.  Is not a bug.  This transfer is not at all meant to be conservative.
It is a _sampling_ transfer.  It samples the source domain at the
destination domain's nodes / elements (depending on if you're transferring
to an elemental or nodal field).

**Comment by vincentlaboure** [comment] 2018-10-04 15:09
Oh I see, thank you for the clarification!
Would there be some documentation available to see what each transfer is designed to do? In particular, I need a conservative transfer working with CONSTANT MONOMIAL but I am not really sure what to use.

**Comment by permcody** [comment] 2018-10-04 16:43
No documentation. We are working to generate it. It takes a lot of time and
we are all so busy. It will be coming.

**Comment by permcody** [comment] 2018-11-15 21:38
Confirmed that an elemental variable cannot be used for the source regardless of the destination.

**Closed** 2018-11-20 15:03 UTC
Labels: C: MOOSE, P: normal, T: task
