### ISSUE TITLE
NavierStokesFV action should be able to handle "tensor" thermal_conductivity

### ISSUE THREAD

**Issue by snschune** [idaholab/moose#21064] opened 2022-05-22 04:58 UTC
## Reason

In highly parameterized flows (aka coarse mesh TH), we use an effective thermal conductivity
in lieu of the actual fluid thermal conductivity. The  `NavierStokesFV` action should support that
need. 

## Design

I am not sure at this point. @grmnptr  what do you think would be the best approach for handling this?
Allow the user to provide a `vector_thermal_conductivity` and then switch the heat conduction 
kernels to "tensor/vector" in the background? The other option would be to ALWAYS use "tensor/vector" 
heat conduction kernels.

## Impact

Potentially the user interface of `NavierStokesFV`.

**Comment by grmnptr** [comment] 2022-05-23 22:46
I would definitely avoid using vector as default. Ideally, we would like to detect if the supplied thermal conductivity is a scalar/vector or tensor. I think we can differentiate between these cases by defining a vector<vector<MooseFunctorName>> and checking the number of elements. If it is 1, we create a regular diffusion kernel. If it is 3 or 9 we create an anisotropic diffusion kernel. What do you think?

**Comment by GiudGiud** [comment] 2022-05-24 18:24
I dont think we need to allow tensor inputs, we just need to allow tensor material property names.

**Comment by grmnptr** [comment] 2022-05-27 14:44
I think this can be closed, duplicate of #21135.

**Closed** 2022-06-19 22:50 UTC
Labels: T: task, C: Modules/Navier Stokes
