### ISSUE TITLE
Enhance mesh extruder

### ISSUE THREAD

**Issue by YaqiWang** [idaholab/moose#3554] opened 2014-07-18 15:52 UTC
We need to enhance the mesh extruder so that it can reassign block IDs for each extruded individual layer. We want to do this enhancement because directly generating a 3D mesh is currently too inefficient to be done.

**Comment by YaqiWang** [comment] 2015-01-22 19:05
I guess @friedmud forgot this one. Please add it into todo list and make it done at your luxury time.

**Comment by permcody** [comment] 2015-01-22 19:08
Will do, however our team's time is at a premium as well with all of us fairly booked out over the next few months. If anyone on your team has time for this, I'd be willing to advise if you need it sooner rather than later.

**Comment by friedmud** [comment] 2015-01-22 23:31
Heh: I'll see if I can get this one next week...

**Comment by YaqiWang** [comment] 2015-08-12 05:11
Let me bring this up again because we do need this and it makes our life easier. We can also use this for z direction refinement study.

**Comment by permcody** [comment] 2015-08-17 14:51
Sounds good, we'll see if we can get to this

**Comment by permcody** [comment] 2015-08-25 20:06
@roystgnr - Here's a feature that was requested a long time ago but nobody has completed it. Basically we want the ability to change subdomain ids of elements inside of the extruded mesh. However I'm not seeing an elegant way of doing this as illustrated here. We don't have a way of retrieving elements of the ith layer in an unstructured mesh. I'm sure I could do something terrible like counting opposite neighbors until I find the desired layer but that seems like a terrible solution. 

Would you be amenable to me adding additional logic to the libMesh side to help out with this enhancement? There are lots of options, I could maintain a data structure that maps the extruded element IDs into an indexable format (i,j,k) so I could do what I want with them in user code. I could send additional information in through an overloaded method that makes use of the existing code, etc. Unless you have any other ideas.

**Comment by roystgnr** [comment] 2015-08-25 23:02
"Counting opposite neighbors" is actually what we did for some shock-fitting code on an extruded-from-surface mesh.  ;-)  In your case it should even work with ParallelMesh, since build_extrusion extrudes the current partitioning as well.

I'd agree that it would be nice to be able to do this at mesh generation time, though.  My preference would be an optional abstract base class argument to MeshGeneration::build_extrusion() which lets you query (old_elem, layer) and returns new_subdomain_id; the first (only?) concrete class would then query old_elem->subdomain_id() and look up that and the layer id in your data structure.

**Comment by permcody** [comment] 2015-08-26 14:35
Sounds good to me, I'll get a PR in when I get a chance.

**Comment by YaqiWang** [comment] 2015-10-07 04:55
@permcody I am reopen this issue because I noticed few things while I am using it:
1. we currently did not check the element type of remapped blocks. Users could remap two blocks in different element type into the same block, which should be error out during extrusion but not now;
2. Is the layer numbered from 1 or 0? If the layer number is bigger than the maximum layer number, will the extruder error out?
3. we need to be able to assign different sizes of layers.

**Comment by permcody** [comment] 2015-10-07 14:31
OK - I'll reopen the issue but it may take some time for me to get to it. I'm currently reworking all of the parsing stuff that you've asked for :)

**Comment by YaqiWang** [comment] 2015-10-31 05:13
How about now? We don't want a known bug sitting in our code plus it's really useful to me.

**Comment by YaqiWang** [comment] 2015-11-04 05:25
Cody I really want this fixed. I can foresee its usage coming soon. I will need some time to test this after the fix. Thanks!

**Comment by permcody** [comment] 2015-11-04 14:31
OK, I'll take a look at this.

**Comment by permcody** [comment] 2015-11-04 15:53
OK so there are at least two bugs here but I don't think either of them affects your simulation. The first issue is that your YakDebugAction is doing something wrong when it's showing you the side sets. If you use `ncdump` or inspect the outputted mesh from Paraview or Peacock there are only 6 sidesets numbered 0, 1, 2, 3, 6, 7. There are no numbers 4 or 5 in the file at all.

The second issue is that we are currently allowing duplicates in BoundaryInfo. If you remove the duplicates from the information in that class, the mesh has the right number elements on each extruded 
side set.

@jwpeterson - I'll open an issue in libMesh to fix the latter issue.

**Comment by YaqiWang** [comment] 2015-11-04 15:56
Oh, do you want to send a patch for YakDebugAction? or I will take a look. The first two issues can be fixed at the mean time.

**Comment by permcody** [comment] 2015-11-04 16:00
Well you should probably patch it, but that's not going to hold me up for looking at the other issues.

**Comment by YaqiWang** [comment] 2015-12-01 02:57
Has this been fixed?

**Comment by permcody** [comment] 2015-12-01 03:47
Well the most egregious bugs should be fixed. @jwpeterson made a few changes to libMesh to disallow the really bad stuff from happening. However, remember that part of the problem is that these where "SHELL" elements not QUADs which never work quite right to begin with. Make sure your source MESH is valid and let us know if you still run into issues. Let's get this ticket closed out.

**Comment by YaqiWang** [comment] 2015-12-15 19:23
I am afraid that we cannot close out this issue yet.

Today I updated MOOSE, Yak and ran the test
```
yak-opt -i extruder_quad.i Debug/print_block_volue=true
```
I got the following
```
 Number of elements = 1700
    Number of nodes = 2142
    Number of sides = 5525
 Blocks:
       1 () : volume 2.87864e-06 with 1700 elements
 Side sets:
       1 () : volume 0.0012495 with 680 sides
       3 () : volume 0.000312374 with 680 sides
       4 () : volume 0 with 0 sides
       5 () : volume 0 with 0 sides
       6 (new_bottom) : volume 0.000287864 with 85 sides
       7 (new_top) : volume 0.000287864 with 85 sides
```
The initial 2D mesh contains 85 elements and two side sets each having 17 sides. The following is the ncdump of the initial mesh:
```
        len_string = 33 ;
	len_line = 81 ;
	four = 4 ;
	time_step = UNLIMITED ; // (0 currently)
	num_dim = 3 ;
	num_nodes = 102 ;
	num_elem = 85 ;
	num_el_blk = 1 ;
	num_qa_rec = 1 ;
	num_side_sets = 2 ;
	num_side_ss1 = 17 ;
	num_df_ss1 = 34 ;
	num_side_ss2 = 17 ;
	num_df_ss2 = 34 ;
	num_el_in_blk1 = 85 ;
	num_nod_per_el1 = 4 ;
```
We extruded the mesh with 20 layers, so the number of sides in 1 and 3 (the original ss IDs) should be 340 but not 680. The top and bottom side sets appear correct. There are still two empty side sets added maybe in `BoundaryInfo`.

ncdump of the extruded mesh confirmed:
```
dimensions:
	len_string = 33 ;
	len_line = 81 ;
	four = 4 ;
	time_step = UNLIMITED ; // (2 currently)
	len_name = 33 ;
	num_dim = 3 ;
	num_nodes = 2142 ;
	num_elem = 1700 ;
	num_el_blk = 1 ;
	num_node_sets = 4 ;
	num_side_sets = 4 ;
	num_el_in_blk1 = 1700 ;
	num_nod_per_el1 = 8 ;
	num_side_ss1 = 680 ;
	num_side_ss2 = 85 ;
	num_side_ss3 = 85 ;
	num_side_ss4 = 680 ;
	num_nod_ns1 = 714 ;
	num_nod_ns2 = 102 ;
	num_nod_ns3 = 102 ;
	num_nod_ns4 = 714 ;
	num_nod_var = 1 ;
	num_info = 222 ;
```
Thanks.

**Comment by jwpeterson** [comment] 2015-12-15 19:47
On Tue, Dec 15, 2015 at 12:27 PM, Yaqi <notifications@github.com> wrote:

> I am afraid that we cannot close out this issue yet.
>
> Today I updated MOOSE, Yak and ran the test under
> moose/test/tests/mesh_modifiers/mesh_extruder
>
> yak-opt -i extruder_quad.i Debug/print_block_volue=true
>
> I got the following
>
>  Number of elements = 1700
>     Number of nodes = 2142
>     Number of sides = 5525
>  Blocks:
>        1 () : volume 2.87864e-06 with 1700 elements
>  Side sets:
>        1 () : volume 0.0012495 with 680 sides
>        3 () : volume 0.000312374 with 680 sides
>        4 () : volume 0 with 0 sides
>        5 () : volume 0 with 0 sides
>        6 (new_bottom) : volume 0.000287864 with 85 sides
>        7 (new_top) : volume 0.000287864 with 85 sides
>
> The initial 2D mesh contains 85 elements and two side sets each having 17
> sides. The following is the ncdump of the initial mesh:
>
>         len_string = 33 ;
>     len_line = 81 ;
>     four = 4 ;
>     time_step = UNLIMITED ; // (0 currently)
>     num_dim = 3 ;
>     num_nodes = 102 ;
>     num_elem = 85 ;
>     num_el_blk = 1 ;
>     num_qa_rec = 1 ;
>     num_side_sets = 2 ;
>     num_side_ss1 = 17 ;
>     num_df_ss1 = 34 ;
>     num_side_ss2 = 17 ;
>     num_df_ss2 = 34 ;
>     num_el_in_blk1 = 85 ;
>     num_nod_per_el1 = 4 ;
>
> We extruded the mesh with 20 layers, so the number of sides in 1 and 3
> (the original ss IDs) should be 340 but not 680. The top and bottom side
> sets appear correct. There are still two empty side sets added maybe in
> BoundaryInfo.
>
> ncdump of the extruded mesh confirmed:
>
> dimensions:
>     len_string = 33 ;
>     len_line = 81 ;
>     four = 4 ;
>     time_step = UNLIMITED ; // (2 currently)
>     len_name = 33 ;
>     num_dim = 3 ;
>     num_nodes = 2142 ;
>     num_elem = 1700 ;
>     num_el_blk = 1 ;
>     num_node_sets = 4 ;
>     num_side_sets = 4 ;
>     num_el_in_blk1 = 1700 ;
>     num_nod_per_el1 = 8 ;
>     num_side_ss1 = 680 ;
>     num_side_ss2 = 85 ;
>     num_side_ss3 = 85 ;
>     num_side_ss4 = 680 ;
>     num_nod_ns1 = 714 ;
>     num_nod_ns2 = 102 ;
>     num_nod_ns3 = 102 ;
>     num_nod_ns4 = 714 ;
>     num_nod_var = 1 ;
>     num_info = 222 ;
>
> Thanks.
>

Yaqi,

Are you using libmesh HEAD?  I don't think the commit I made fixing this
issue (libmesh:2a37a057, Nov 4) in BoundaryInfo has made it into the
libmesh submodule of MOOSE yet (currently at libmesh:62fdf8c, Oct 22).

It has been a while since the last libmesh update (no one wants to merge my
libmesh update PR for some reason :).

-- 
John

**Comment by YaqiWang** [comment] 2015-12-15 20:22
Gosh, maybe not. I am using MOOSE submodule.

`git log` under libmesh gives:
```
commit 62fdf8cd12e7706458bae59081ecea287c0d70d6
Merge: 0e88168 fb91405
Author: David Knezevic <david.knezevic@akselos.com>
Date:   Thu Oct 22 10:28:57 2015 -0400

    Merge pull request #686 from dknez/copy_node_boundary_info
    
    We should copy over node boundary data when we do BoundaryInfo::sync

commit 0e881688c409616d7dc0fd38f1294321adb8316f
Author: Benjamin S. Kirk <benjamin.kirk@nasa.gov>
Date:   Thu Oct 22 08:48:30 2015 -0500

    fix function implementation (barebones) to match prototype
```
I guess it is pretty outdated.

**Comment by permcody** [comment] 2015-12-15 20:23
Right, we need a libMesh update...

**Comment by jwpeterson** [comment] 2015-12-15 20:25
If you have a minute, would you mind trying your particular example with libmesh HEAD (I can give you more detailed instructions for building it if you need).  Then we'll know for sure if that bugfix works for you.

**Comment by YaqiWang** [comment] 2015-12-15 20:26
Sure. John, can you stop by and help me update libmesh to HEAD?

**Comment by YaqiWang** [comment] 2015-12-15 21:28
John, to make you aware, after update to head and compile, I got this compiling warning all over:

```
In file included from /Users/wangy2/projects/moose/scripts/../libmesh/installed/include/libmesh/auto_ptr.h:52:
/Users/wangy2/projects/moose/scripts/../libmesh/installed/include/libmesh/unique_ptr.hpp:26:34: warning: unknown warning group '-Wunused-local-typedef', ignored [-Wunknown-pragmas]
```
for almost every source file.

**Comment by YaqiWang** [comment] 2015-12-15 21:42
Now the print-out is
```
 Number of elements = 1700
    Number of nodes = 2142
    Number of sides = 5525
 Blocks:
       1 () : volume 2.87864e-06 with 1700 elements
 Side sets:
       1 () : volume 0.000624748 with 340 sides
       3 () : volume 0.000156187 with 340 sides
       4 () : volume 0 with 0 sides
       5 () : volume 0 with 0 sides
       6 (new_bottom) : volume 0.000287864 with 85 sides
       7 (new_top) : volume 0.000287864 with 85 sides
```
The extruded side sets are not having the correct numbers. The only issue is that there is still two empty side sets. This is minor. Up to you if you want to take a look at this or not. The exodus output file seems all fine.

**Comment by jwpeterson** [comment] 2015-12-15 21:46
> John, to make you aware, after update to head and compile, I got this compiling warning all over:

Hmm.. what compiler?  I have a 
```
#ifdef __clang__
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wunused-local-typedef"
#endif
```
that should clean up that warning.

**Comment by jwpeterson** [comment] 2015-12-15 21:48
> The extruded side sets are not having the correct numbers.

You mean they *do* have the correct numbers?



> The only issue is that there is still two empty side sets.

Ah, yes, that is caused by the code which changes a sideset's number from X to Y, the original sideset with id X is still there, it is just empty.  I can probably fix that too...

**Comment by jwpeterson** [comment] 2015-12-15 21:49
> in that file that should clean up that warning.

Oops, on closer reading, I see that this pragma is actually *causing* the warning!  So it must be a clang version thing.

**Comment by YaqiWang** [comment] 2015-12-15 21:52
yep. If those two annoying empty side sets can be gone, it will be great!

**Comment by permcody** [comment] 2015-12-15 22:11
On Tue, Dec 15, 2015 at 2:51 PM John W. Peterson <notifications@github.com>
wrote:

> The extruded side sets are not having the correct numbers.
>
> You mean they *do* have the correct numbers?
>
> The only issue is that there is still two empty side sets.
>
> Ah, yes, that is caused by the code which changes a sideset's number from
> X to Y, the original sideset with id X is still there, it is just empty. I
> can probably fix that too...
>

Yaqi - I don't see those empty sidesets in the output file. I know they are
coming from your own debugging code somewhere but I don't think they are in
the mesh at all.

**Comment by YaqiWang** [comment] 2015-12-15 22:15
Yes, they are not in the output exodus file. They are possibly filtered out during output. They are in the `BoundaryInfo` I think. The debugging code in Yak is extremely simple and just accessor, so should not be problematic.

**Comment by YaqiWang** [comment] 2016-01-13 16:33
I tried the latest libmesh submodule in MOOSE, the problems are all solved. So I will close this issue. We can create a new issue if the unevenly distribution of the grid in the extruded direction is necessary. Thank you all very much!

**Comment by YaqiWang** [comment] 2016-08-08 17:02
I plan to add two new parameters `layer_sizes` and `num_sub_layers` in replace of `num_layers`, so that we can non-uniformly distribute the extruded layers. The total number of layers will the summation of `num_sub_layers`, which specifies the sub-division of the layers given in the first parameter. Also with these two parameters, `extrusion_vector` will only contain the extrusion direction information, i.e. its L2 norm will be restricted to one.

**Comment by YaqiWang** [comment] 2016-08-09 19:46
I initially planned to have a two step method for this extension: extrude the mesh uniformly and then loop through mesh nodes to change there coordinates. But this seems impossible because we are allowing the initial mesh to have the non-zero (x,y,z) coordinates, which makes no way to recognize on which layer the extruded nodes are by just looking at their coordinates. We can use this approach only when we restrict the mesh on a plane. So I decided to only extrude mesh with non-zero x (1D), x and y (2D) in my application. @permcody If you have any other thoughts we can reopen this issue. Thanks.

**Comment by YaqiWang** [comment] 2016-08-11 18:21
To make the customized mesh extruder in my app, I have to change the code in `MeshExtruder` a little to be able to reuse them. A small issue will be fixed: the node sets names are not renames as for the side set names when `top_sideset` or `bottom_sideset` present.

**Closed** 2016-08-12 17:08 UTC
Labels: C: MOOSE, P: normal, T: task
