### ISSUE TITLE
Preserve block and boundary names in `CombinerGenerator`

### ISSUE THREAD

**Issue by joshuahansel** [idaholab/moose#22838] opened 2022-11-30 22:30 UTC
## Reason
The generator should not delete block and boundary names. Currently, only the block and boundary names of the first generator in `inputs` are preserved; the others are discarded. While it may sometimes be possible to just name blocks and boundaries after the `CombinerGenerator`, this is not always possible. For example, if meshes are generated in THM, the block/boundary IDs are unknown to the user, so `RenameBlockGenerator` and `RenameBoundaryGenerator` are not usable (and it would be very tedious in most cases anyway).

## Design
This would preserve all block and boundary names. There is some ambiguity when the inputs share block and boundary IDs. In this case, a warning should be given when names are discarded (maybe with the ability of the user to suppress the warning). Also, I recommend an option for the user to specify that the various inputs should not share any IDs (and if they do, give an error), since it can be easy to inadvertently merge blocks and boundaries. And maybe there should even be an option to make all of the IDs unique without making the user do it.

## Impact
There would be no impact to existing usage of `CombinerGenerator`. Additional functionality will be added.

**Comment by aprilnovak** [comment] 2022-12-01 01:13
I was just recently running into this exact issue with `CombinerGenerator` (inadvertently merging boundaries). The user can try to rename those boundaries before using `CombinerGenerator`, but with string names only the `BoundaryName` gets changed (and I don't think there's an interface to rename the identical `BoundaryID`s, which is one cause of merging).

I think it'd be great for the generator to automatically rename any boundary IDs that are duplicated across the mesh `inputs`.

**Comment by joshuahansel** [comment] 2022-12-01 13:44
> and I don't think there's an interface to rename the identical BoundaryIDs

Just to be clear, `RenameBoundaryGenerator` can do both the assigning/renaming of boundary names and also the changing of boundary IDs, and similarly for `RenameBlockGenerator`, but you might not be saying otherwise.

**Comment by aprilnovak** [comment] 2022-12-01 17:15
Thanks for clarifying - I was looking at the `new_boundary_id` parameter being deprecated, and didn't realize that you could  pass in a boundary ID for a `BoundaryName` input param. In either case, this issue will still resolve my issue - I think `CombinerGenerator` doesn't just "disappear" the IDs/names of the other input meshes, they are merged together (giving the appearance of them disappearing). Maybe you are saying the same thing. 

Here's a small example that uses `CombinerGenerator` to combine 2 meshes. The original meshes have 1 element/sideset:

- mesh with sidesets 0 (bottom) , 1 (right), 2 (top), 3 (left), 4 (other)
- mesh with sidesets 0 (bottom), 1 (right), 2 (top), 3 (left), 4 (again)

Merging them together will "add" the sidesets, but only keep the names of the first mesh. Resulting mesh has 2 elements per sideset, indicating that "other" and "again" were merged together:

- mesh with sidesets 0 (bottom), 1 (right), 2 (top), 3 (left), 4 (other)

```
  # FIRST MESH: four sidesets: 0 (bottom), 1 (right), 2 (top), 3 (left), 4 (other)
  [gmg]
    type = GeneratedMeshGenerator
    dim = 2
  []
  [create_another]
    type = SideSetsFromNormalsGenerator
    input = gmg
    normals = '1 0 0'
    new_boundary = 'other'
  []



  # SECOND MESH: four sidesets: 0 (bottom), 1 (right), 2 (top), 3 (left), 4 (again)
  [gmg2]
    type = GeneratedMeshGenerator
    dim = 2
  []
  [create_another2]
    type = SideSetsFromNormalsGenerator
    input = gmg2
    normals = '1 0 0'
    new_boundary = 'again'
  []



  # MERGED MESH: four sidesets 0 (bottom), 1 (right), 2 (top), 3 (left), 4 (other)
  [combine]
    type = CombinerGenerator
    inputs = 'create_another create_another2'
  []
```

If this is intended behavior, then disregard! It just took me a long time to figure out what was going on, because I thought I was doing my due diligence by changing the boundary name with a `RenameBoundaryGenerator`.

**Comment by joshuahansel** [comment] 2022-12-01 18:10
Right, I'm saying that just the *names* of the secondary meshes are discarded; the IDs are preserved, along with any names the first mesh had associated to them.

**Closed** 2023-05-01 18:40 UTC
Labels: T: task, C: Meshing

**Comment by MengnanLi91** [comment] 2023-06-22 20:11
@GiudGiud the issue you mentioned seems already fixed here
