### ISSUE TITLE
Make getting started flow better for site visitors

### ISSUE THREAD

**Issue by rwcarlsen** [idaholab/moose#12453] opened 2018-11-08 00:38 UTC
## Rationale

The framework website isn't the best at directing new users toward other relevant pages on the site and at telling them what to do next.  

## Description

We should have a proper getting started page that we mention and link to directly in the main page's body (not just through navigation).  We should also direct people toward examples/tutorial better instead of abandoning them to wander the site aimlessly after they compile a new application.

## Impact

Help new users learn about and get addicted to moose more effectively.

**Comment by milljm** [comment] 2018-11-08 14:55
duplicate of #12328

**Comment by permcody** [comment] 2019-11-06 22:55
Several PRs above have improved the flow - closing this issue.

**Closed by permcody** 2019-11-06 22:55 UTC
Labels: C: Documentation
