### ISSUE TITLE
Order dependency in the input file among UserObjects

### ISSUE THREAD

**Issue by permcody** [idaholab/moose#6254] opened 2016-01-28 15:47 UTC
See https://groups.google.com/d/msgid/moose-users/d5a97589-2bab-48bd-806f-76ac847ff477%40googlegroups.com?utm_medium=email&utm_source=footer

**Comment by permcody** [comment] 2016-02-22 17:08
Notes: Doesn't appear to be related to types, there is a input file order dependency for UOs and possibly materials. Perhaps this is related to all the warehouse refactoring? Maybe, maybe not.

Also see #6360.

**Comment by aeslaughter** [comment] 2016-02-22 22:16
The UserObject warehouse has not been updated yet, the Materials has. If
Materials are order dependent then there may be a case where
MooseObjectWarehouse::sort is not being called, which should happen in
FEProblem::initialSetup, just before initialSetup is called on the objects.

There is certainly ordering issues, the only type of UserObject that gets
sorted is GeneralUserObject all others are constructed in order as defined
in the input file.

For reference, only objects inheriting from `DependencyResolverInterface`
are sorted:
http://mooseframework.org/docs/doxygen/moose/classDependencyResolverInterface.html,
all others are constructed in order.

**Comment by permcody** [comment] 2016-02-22 22:22
These are probably existing issues. The problem with this particular issue is it caused by a call to `getUserObject<T>()` which is and generally should be in the object constructor. To fix this kind of issue, we'd have to make a sorting decision on the parameters, not the objects themselves, or we'd have to have a shim class that would allow us to retrieve non-existent references that would be filled in later.

**Comment by aeslaughter** [comment] 2016-02-22 22:32
We could also make in an error to call getUserObject outside of a
constructor. I did something similar with copying of InputParameters, where
after construction I set a parameter so that subsequent copies cause a
MooseError. I am sure we could probably come up with something similar with
getUserObject.

**Comment by permcody** [comment] 2016-02-22 23:24
I don't want it to be an error to call those kinds of things outside of the
constructor. There's always some case where somebody wants to do it in
initialSetup (which is fine as long as they don't mind pointers instead of
refs).

**Comment by aeslaughter** [comment] 2016-02-23 15:49
We could make it an error after initialSetup then.

**Comment by lindsayad** [comment] 2022-06-01 18:56
duplicate of #7879

**Closed by lindsayad** 2022-06-01 18:56 UTC
Labels: C: Framework, T: defect, P: normal
