### ISSUE TITLE
User objects ordering in input file can matter

### ISSUE THREAD

**Issue by YaqiWang** [idaholab/moose#14654] opened 2020-01-28 20:03 UTC
## Reason
Our design currently is to make the input subblock ordering irrelevant. This is true for kernels, materials, etc. but can be false for user objects. If we have one user object depend on another user object by calling `getUserObject` in its constructor. The call can fail if the other user object is not constructed, which means we have to have a certain ordering in the input to make this work.

## Design
There are ways to fix this. I do not quite like the late binding way, because then we cannot call certain functions of the another user object in the constructor of the user object. Using input parameters to resolve the dependency and fix the ordering internally seems a better solution to me.

## Impact
Minor because we have ways to bypass this including using actions.

**Comment by lindsayad** [comment] 2022-06-02 19:36
duplicate of #7879

**Closed by lindsayad** 2022-06-02 19:36 UTC
Labels: C: Framework, T: task, P: normal
