### ISSUE TITLE
Failed installation tests

### ISSUE THREAD

**Issue by VictorEijkhout** [idaholab/moose#12423] opened 2018-11-02 04:21 UTC
```
[c455-071 moose:1] make test
cd /work/00434/eijkhout/moose/moose-stampede2/test && \
  METHOD=opt make -j8 && \
  export MOOSE_MPI_COMMAND="/home1/00434/eijkhout/Software/moose/mpiexecv" && \
  ./run_tests -j8
make[1]: Entering directory `/work/00434/eijkhout/moose/moose-stampede2/test'
Compiling C++ (in opt mode) /work/00434/eijkhout/moose/moose-stampede2/framework/build/unity_src/problems_Unity.C...
Compiling C++ (in opt mode) /work/00434/eijkhout/moose/moose-stampede2/test/build/unity_src/userobjects_Unity.C...
Compiling C++ (in opt mode) /work/00434/eijkhout/moose/moose-stampede2/test/build/unity_src/kernels_Unity.C...
Compiling C++ (in opt mode) /work/00434/eijkhout/moose/moose-stampede2/test/build/unity_src/bcs_Unity.C...
Compiling C++ (in opt mode) /work/00434/eijkhout/moose/moose-stampede2/test/build/unity_src/problems_Unity.C...
make[1]: *** No rule to make target `/work/00434/eijkhout/moose/moose-stampede2/scripts/../libm', needed by `/work/00434/eijkhout/moose/moose-stampede2/test/build/unity_src/indicators_Unity.x86_64-unknown-linux-gnu.opt.lo'.  Stop.
make[1]: *** Waiting for unfinished jobs....
make[1]: Leaving directory `/work/00434/eijkhout/moose/moose-stampede2/test'
make: *** [test] Error 2
[c455-071 moose:2] ls /work/00434/eijkhout/moose/moose-stampede2/scripts/..
COPYING  COPYRIGHT  examples/  framework/  gui@  large_media/  libmesh/  LICENSE  modules/  python/  README.md  scripts/  stork/  test/  tutorials/  unit/
[c455-071 moose:3] ldd /work/00434/eijkhout/moose/moose-stampede2/test/build/unity_src/indicators_Unity.x86_64-unknown-linux-gnu.opt.lo
ldd: /work/00434/eijkhout/moose/moose-stampede2/test/build/unity_src/indicators_Unity.x86_64-unknown-linux-gnu.opt.lo: No such file or directory
[c455-071 moose:4] ldd /work/00434/eijkhout/moose/moose-stampede2/test/build/unity_src/indicators_Unity.x86_64-unknown-linux-gnu.opt.lo.d
ldd: warning: you do not have execution permission for `/work/00434/eijkhout/moose/moose-stampede2/test/build/unity_src/indicators_Unity.x86_64-unknown-linux-gnu.opt.lo.d'
        not a dynamic executable
```

Let me know what you need from me.

**Comment by jwpeterson** [comment] 2018-11-02 15:06
The relevant error here seems to be this one:
```
*** No rule to make target `/work/00434/eijkhout/moose/moose-stampede2/scripts/../libm', needed by `/work/00434/eijkhout/moose/moose-stampede2/test/build/unity_src/indicators_Unity.x86_64-unknown-linux-gnu.opt.lo'.  Stop.
```

I have no idea why a script that presumably you created (?) which is called "libm" would show up as a dependency for any of our source code... It might be possible to get more information if you run `make -n` so that make will print the commands it *thinks* it should run. We may be able to track down the problem from there...

**Comment by VictorEijkhout** [comment] 2018-11-02 17:54
On Nov 2, 2018, at 10:06 AM, John W. Peterson <notifications@github.com<mailto:notifications@github.com>> wrote:

I have no idea why a script that presumably you created (?) which is called “libm"

Of course I made no such thing. It seems the error messages are truncated, and “libm” is the first couple of characters of “libmesh”. Note that


ndicators_Unity.x86_64-unknown-linux-gnu.opt.lo

is also a truncated name.

But that libmesh directory is actually there.

[staff moose:26] ls /work/00434/eijkhout/moose/moose-stampede2/
COPYING  COPYRIGHT  examples/  framework/  gui@  large_media/  libmesh/  LICENSE  modules/  python/  README.md  scripts/  stork/  test/  tutorials/  unit/


would show up as a dependency for any of our source code... It might be possible to get more information if you run make -n so that make will print the commands it thinks it should run. We may be able to track down the problem from there...

New installation.

echo Creating Unity Directory /work/00434/eijkhout/stampede2/moose-stampede2/framework/build/unity_src
mkdir -p  /work/00434/eijkhout/stampede2/moose-stampede2/framework/build/unity_src
/bin/sh: /work/00434/eijkhout/stampede2/moose-stampede2/framework/build/unity_src/src_Unity.C: No such file or directory
echo Creating Unity /work/00434/eijkhout/stampede2/moose-stampede2/framework/build/unity_src/src_Unity.C
echo "Compiling C++ (in "opt" mode) "/work/00434/eijkhout/stampede2/moose-stampede2/framework/build/unity_src/src_Unity.C"..."
/work/00434/eijkhout/stampede2/moose-stampede2/libmesh/installed/contrib/bin/libtool  --tag=CXX  --mode=compile --quiet mpicxx -DNDEBUG -Wall -Wextra -DMOOSE_TEST_ENABLED -O3 -unroll -w0 -ftz -fopenmp -DMETHOD=opt  -I/work/00434/eijkhout/stampede2/moose-stampede2/framework/build/header_symlinks  -I/work/00434/eijkhout/stampede2/moose-stampede2/framework/contrib/boost/include  -I/work/00434/eijkhout/stampede2/moose-stampede2/framework/contrib/jsoncpp/include  -I/work/00434/eijkhout/stampede2/moose-stampede2/framework/contrib/jsoncpp/include/json  -I/work/00434/eijkhout/stampede2/moose-stampede2/framework/contrib/mtwist/include  -I/work/00434/eijkhout/stampede2/moose-stampede2/framework/contrib/pcre/include  -I/work/00434/eijkhout/stampede2/moose-stampede2/framework/contrib/tinydir/include  -I"/work/00434/eijkhout/stampede2/moose-stampede2/framework/contrib/gtest"  -I"/work/00434/eijkhout/stampede2/moose-stampede2/framework/contrib/hit" -I/work/00434/eijkhout/stampede2/moose-stampede2/scripts/../libmesh/installed/include -I/home1/apps/intel18/impi18_0/petsc/3.10//include -I/home1/apps/intel18/impi18_0/petsc/3.10//skylake/include -I/home1/apps/intel18/impi18_0/petsc/3.10/skylake/include -I/home1/apps/intel18/impi18_0/petsc/3.10/include -I/opt/apps/intel18/impi18_0/phdf5/1.8.16/x86_64/include -I/opt/intel/compilers_and_libraries_2018.2.199/linux/mpi/intel64/include -I/opt/apps/intel18/boost/1.68/include -I/work/00434/eijkhout/stampede2/moose-stampede2/test/build/header_symlinks  -I/work/00434/eijkhout/stampede2/moose-stampede2/scripts/../libmesh/installed/include -I/home1/apps/intel18/impi18_0/petsc/3.10//include -I/home1/apps/intel18/impi18_0/petsc/3.10//skylake/include -I/home1/apps/intel18/impi18_0/petsc/3.10/skylake/include -I/home1/apps/intel18/impi18_0/petsc/3.10/include -I/opt/apps/intel18/impi18_0/phdf5/1.8.16/x86_64/include -I/opt/intel/compilers_and_libraries_2018.2.199/linux/mpi/intel64/include -I/opt/apps/intel18/boost/1.68/include -MMD -MP -MF /work/00434/eijkhout/stampede2/moose-stampede2/framework/build/unity_src/src_Unity.x86_64-unknown-linux-gnu.opt.lo.d -MT /work/00434/eijkhout/stampede2/moose-stampede2/framework/build/unity_src/src_Unity.x86_64-unknown-linux-gnu.opt.lo -c /work/00434/eijkhout/stampede2/moose-stampede2/framework/build/unity_src/src_Unity.C -o /work/00434/eijkhout/stampede2/moose-stampede2/framework/build/unity_src/src_Unity.x86_64-unknown-linux-gnu.opt.lo
/bin/sh: /work/00434/eijkhout/stampede2/moose-stampede2/framework/build/unity_src/userobject_Unity.C: No such file or directory


and in fact


[staff moose:37] ls /work/00434/eijkhout/stampede2/moose-stampede2/framework/build/
header_symlinks/

**Comment by permcody** [comment] 2018-11-06 16:04
libm may actually just be the normal math library. I don't think it's truncated. Any other progress here?

**Comment by VictorEijkhout** [comment] 2018-11-06 16:09
On Nov 6, 2018, at 10:04 AM, Cody Permann <notifications@github.com<mailto:notifications@github.com>> wrote:

Any other progress here?

See the rest of my last reply: “make test” fails by trying to compile a non-existing file.

V.

**Comment by permcody** [comment] 2018-11-06 16:21
> mkdir -p  /work/00434/eijkhout/stampede2/moose-stampede2/framework/build/unity_src
/bin/sh: /work/00434/eijkhout/stampede2/moose-stampede2/framework/build/unity_src/src_Unity.C: No such file or directory

Is there a permissions problem here somewhere? As part of the make process the build directory and two temporary directories are created: "header_symlinks" and "unity_src". These directories are built and populated with simple shell commands that drastically speed up compilation. Here is a sample of what these directories typically contain after running make:

symlinks:
```

**Comment by VictorEijkhout** [comment] 2018-11-06 16:33
On Nov 6, 2018, at 10:21 AM, Cody Permann <notifications@github.com<mailto:notifications@github.com>> wrote:


Here is a sample of what these directories typically contain after running make:

symlinks:





That’s an incomplete post?

Victor.

**Comment by permcody** [comment] 2018-11-06 16:39
Yes, I accidentally hit enter, It's been edited.

**Comment by VictorEijkhout** [comment] 2018-11-07 00:09
> As part of the make process the build directory and two temporary directories are created: "header_symlinks" and "unity_src".

I can't find these.

```
[staff moose:79] cd moose-stampede2/
[staff moose-stampede2:80] ls
COPYING  COPYRIGHT  examples/  framework/  gui@  large_media/  libmesh/  LICENSE  modules/  python/  README.md  scripts/  stork/  test/  tutorials/  unit/
[staff moose-stampede2:81] find . -type d -name \*symlinks\*
[staff moose-stampede2:82] find . -type d -name \*unity_src\*
[staff moose-stampede2:83] ls -l LICENSE
-rw-r--r-- 1 eijkhout G-25072 26530 Nov  6 11:16 LICENSE
```
[libmeshlog.zip](https://github.com/idaholab/moose/files/2555554/libmeshlog.zip)

**Comment by permcody** [comment] 2018-11-07 17:21
The "build" directory gets created in each "application". So in MOOSE, you'll get one in the "framework" directory and in the "test" directory and down inside of each module if you build those. It's unclear if those got created or not from your original post. 

We create those directories inside the makefile with shell commands:
https://github.com/idaholab/moose/blob/next/framework/moose.mk#L66-L71

If that's not happening, is it due to some shell issue? permissions? Perhaps you can shed some light based on your knowledge of the system you are working with.

**Comment by VictorEijkhout** [comment] 2018-11-07 18:05
> The "build" directory gets created in each "application". So in MOOSE, you'll get one in the "framework" directory and in the "test" directory and down inside of each module if you build those.

What does “those" refer to?

> If that's not happening, is it due to some shell issue? permissions?

Pretty sure that there are no permission problems. I’m doing everything in my ordinary user account. Did you look at my long log file? Does it report on everything it should have?

Victor.

**Comment by permcody** [comment] 2018-11-07 18:13
> What does “those" refer to?
 
The individual modules (e.g. modules/phase_field, modules/tensor_mechanics, etc)

>Pretty sure that there are no permission problems. I’m doing everything in my ordinary user account. Did you look at my long log file? Does it report on everything it should have?

From what I gather in your log file, libMesh built and installed successfully. So it appears that the problem doesn't occur until you start building MOOSE. I believe the problem is that somehow the build directory and subdirectories are not getting properly created or populated on your system. 

Do you have a moose/framework/build directory? If so does it contain "unity_src" and "header_symlinks"? Based on one of your previous responses, I'm thinking the answer is no. If not, perhaps you could manually create those directories and at least see if our Makefile can at least populate those directories. They should be filed with autogenerated ".C" files and soft links to headers in the corresponding include tree. If that's not happening, we'll at least have narrowed in on the specific issue.

Moving forward, perhaps we could obtain an account on Stampede to assist with building? I'm fairly certain we've worked with administrators on that system before and had something working in the past.

**Comment by VictorEijkhout** [comment] 2018-11-07 18:20
Do you have a moose/framework/build directory?

Doesn’t seem so.

[staff moose-stampede2:94] ls
COPYING  COPYRIGHT  examples/  framework/  gui@  large_media/  libmesh/  LICENSE  modules/  python/  README.md  scripts/  stork/  test/  tutorials/  unit/
[staff moose-stampede2:95] ls framework/
app.mk  build.mk  build_support/  contrib/  doc/  include/  Makefile  moose.mk  notes.md  scripts/  src/
[staff moose-stampede2:96]


Moving forward, perhaps we could obtain an account on Stampede to assist with building?

Go to portal.tacc.utexas.edu<http://portal.tacc.utexas.edu> and create an account. I’ll get you added to a project so that you can log in.

Victor.

**Comment by VictorEijkhout** [comment] 2018-11-07 20:18
On Nov 7, 2018, at 12:13 PM, Cody Permann <notifications@github.com<mailto:notifications@github.com>> wrote:

Moving forward, perhaps we could obtain an account on Stampede to assist with building?

JohnP has been added to a project. He can now use stampede2.

Victor.

**Comment by jwpeterson** [comment] 2018-11-12 17:54
Since you are building in `/work`: are there location-dependent [extended ACLs](https://unix.stackexchange.com/questions/196441/mkdir-permissions-do-not-correspond-to-umask-change-depending-on-location) on your system that give directories different permissions than what your normal umask would imply?

It was helpful seeing your file permissions for the `LICENSE` file, but what are your file permissions for the `moose-stampede2` directory itself?

I am going to log in to stampede2 myself now and give it a try, I will let you know what I find.

**Comment by jwpeterson** [comment] 2018-11-12 22:35
I can report that MOOSE builds fine for me on stampede2 in my home directory. Next I will try building in `/work`. 

Note that I added the following to my .bashrc file:
```
module purge
module load intel/18.0.0 impi/18.0.0 petsc/3.10 git xalt
```

@VictorEijkhout we had discussed building/deploying a libmesh/1.3.1 module but I don't see it currently. Has there not been a maintenance since then?

**Comment by VictorEijkhout** [comment] 2018-11-13 01:32
module load intel/18.0.0 impi/18.0.0 petsc/3.10 git xalt

Could you use intel/18.0.2 ? That’s the current standard.

@VictorEijkhout<https://github.com/VictorEijkhout> we had discussed building/deploying a libmesh/1.3.1 module

It will be rolled out in the next maintainance.

V.

**Comment by jwpeterson** [comment] 2018-11-13 15:04
> Could you use intel/18.0.2 ? That’s the current standard.

I'm sure I could, but I don't really understand why it's necessary? Do you think the slightly updated Intel version is causing the errors you are seeing?

**Comment by VictorEijkhout** [comment] 2018-11-13 15:12
On Nov 13, 2018, at 9:04 AM, John W. Peterson <notifications@github.com<mailto:notifications@github.com>> wrote:

I'm sure I could, but I don't really understand why it's necessary?

It’s not. Never mind.

V.

**Comment by permcody** [comment] 2019-11-06 22:51
Closing as there really isn't any open issue here. This is a support ticket.

**Closed by permcody** 2019-11-06 22:51 UTC
Labels: C: MOOSE, P: normal, T: task

**Comment by lizuosheng** [comment] 2021-11-04 08:08
Compiling C++ (in opt mode) /mnt/c/For_MOOSE/projects/moose/framework/build/unity_src/dgkernels_Unity.C...
{standard input}: Assembler messages:
{standard input}:326378: Warning: end of file not at end of a line; newline inserted
{standard input}:327582: Error: bad register name `%'
{standard input}: Error: open CFI at the end of file; missing .cfi_endproc directive
x86_64-conda-linux-gnu-c++: fatal error: Killed signal terminated program cc1plus
compilation terminated.
/mnt/c/For_MOOSE/projects/moose/framework/build.mk:144: recipe for target '/mnt/c/For_MOOSE/projects/moose/framework/build/unity_src/outputs_Unity.x86_64-conda-linux-gnu.opt.lo' failed
make: * [/mnt/c/For_MOOSE/projects/moose/framework/build/unity_src/outputs_Unity.x86_64-conda-linux-gnu.opt.lo] Error 1
make: * Waiting for unfinished jobs....


why?????

**Comment by permcody** [comment] 2021-11-04 14:18
This ticket has been closed for 2 years. I recommend you reach out for support on our discussions board with installation issues. We have a special area for that.
