### ISSUE TITLE
Mesh does not allow small values

### ISSUE THREAD

**Issue by itgreenquist** [idaholab/moose#5249] opened 2015-06-15 22:05 UTC
I have been trying to run a simulation with a mesh only 25 nm across. I set xmax (and ymax) to 25e-9. Before the simulation even begins, I get an error:
'Trying to retrieve automatic paired mapping for a mesh that is not regular and orthogonal'
from MooseMesh.C, line 1371.

After looking into it for a while, I think the problem is in MooseMesh.h, either in line 417 or 521, where it specifies a tolerance for spacing between nodes of 1e-6. Would it be possible to make this tolerance a parameter that can be overridden for very small meshes?

**Comment by dschwen** [comment] 2015-06-15 22:18
Yeah, instead of making this a default argument we should add an InputParameter that could default to ```libMesh::TOLERANCE``` instead.
I remember I ran into the same issue a few months ago. I cannot, however, remember why I didn't do that back then. I wonder if there are further spots where tolerances are used to check node locations.

**Comment by permcody** [comment] 2015-06-16 01:38
@dschwen that's a good plan. We have a few of these hard-coded tolerances floating around in the framework. Most of them are harmless, until they aren't!

**Comment by friedmud** [comment] 2015-06-18 14:39
Possibly... but @itgreenquist even if you get past this your simulation will most likely not work with such a small domain.  Precision loss with tiny numbers will keep you from getting convergence.

You need to change your units to nm so that your domain will be "25" across.  In general this will provide for a much more robust code.

**Comment by jwpeterson** [comment] 2015-06-18 14:45
:+1: using elements with Jacobian O(1e-9) is asking for trouble.  There will also be routines in libmesh PointLocator that will just return strange results on a Mesh that small.

**Comment by friedmud** [comment] 2015-06-18 14:46
I'm going to go ahead and close this.  @itgreenquist if you have any questions about how to rescale your equations just let us know on the moose-users mailing list.  We can definitely help you out.

**Closed by friedmud** 2015-06-18 14:46 UTC
Labels: C: MOOSE, P: normal, T: task

**Comment by dschwen** [comment] 2015-06-18 15:23
I have real trouble believing the point about precision loss in tiny numbers. We are dealing with _double_ precision here! In this concrete example looking at the amount ov available double precision numbers between 0 and 25 you will find that **over 97%** of the available numbers are in the interval 0 to 2.5e-8! I would argue that simply scaling down values 9 orders of magnitude will have no significant loss of precision.

**Comment by dschwen** [comment] 2015-06-18 15:30
As to @jwpeterson's point about the small Jacobian values: Isn't that what we have residual scaling for? I assume it scales the jacobians as well, right? The main issues I can see are fixed tolerances in the point locator (needed for PBCs for example) and the PETSc zero thresholds (which could be adjusted).
I've seen the issue of using small meshes come up multiple times now and just telling people to switch units does not sound like a fully satisfactory solution to me. Per my comment above I'd argue that there should not be any intrinsic numerical issues with numbers a dozen magnitudes around 1.
In Ian's case we are trying to implement a benchmark problem that is comparing MOOSE phase field directly to a number of other packages. I feel that by rescaling units we'd be cheating a bit, if the competition can deal with the given units. Not to mention that rescaling a black box free energy functional that was handed to you without units attached to the parameters is a pain in the butt.

**Comment by andrsd** [comment] 2015-06-18 15:45
> As to @jwpeterson's point about the small Jacobian values: Isn't that what we have residual scaling for?

@jwpeterson is talking about Jacobian of the elements (i.e. the one related to computation of JxW for integration), not Jacobian of one's PDE. Residual scaling would not obviously help here...

**Comment by dschwen** [comment] 2015-06-18 15:56
Yeah, ok, but still, who cares, those only enter multiplicative, which incurs almost no loss of precision. The only scenario where orders of magnitude matter are addition and subtraction, where you are limited by the significant digits. But you only ever add/subtract numbers that have the _same_ units, i.e. that scale in the _same_ way when you do a unit change. I really think this is a non-problem.

**Comment by friedmud** [comment] 2015-06-18 16:03
Well.  You're within your rights to think... but as someone that's tried this multiple times (most recently with Mike Short for a small paper we just submitted) I can tell you it doesn't work well.

Every time I try it I relearn that changing units is absolutely necessary.  In the most recent attempt the linear/nonlinear convergence would just stall (even with scaling).  Once we rescaled the problem everything converged perfectly.

**Comment by dschwen** [comment] 2015-06-18 16:16
Well thanks, a phenomenological observation is fine, but I'd really like to know **why** this should be an issue. I cannot see any difference between rescaling units and and rescaling the residual and Jacobian. But maybe I'm missing something here. "precision loss" due to "tiny" numbers certainly cannot be the cause.

**Comment by amjokisaari** [comment] 2015-06-25 16:38
Late to the party, but I agree with @dschwen.  As a scientist first, I don't think it's a good idea to simply tell people "rescale your units" without an explanation of why this is necessary for this piece of software.  If competing software can deal with it (maybe there is some internal scaling done without user knowledge?) then MOOSE looks a little rough if it can't and there's not a good explanation.

> Not to mention that rescaling a black box free energy functional that was handed to you without units attached to the parameters is a pain in the butt.

Very, very true.

**Comment by friedmud** [comment] 2015-06-30 13:30
@amjokisaari it's not a MOOSE thing... it's a finite-elements with Krylov solvers thing.  It certainly happens with just pure libMesh and PETSc.  I'm fairly confident that it would happen with just pure PETSc.

What software have you used that allows this?

**Comment by amjokisaari** [comment] 2015-06-30 16:23
@friedmud, I believe you.  I haven't tried other FE software, I was more just agreeing with @dschwen's sentiment in general.  I see how that could be confusing.  However, I will say that the finite difference code that I wrote for troubleshooting phase field free energy functionals has no problem working with length in nanometers, energy in J/m^3, and very small dt.  Coming from the user/physical scientist perspective, I naively would not expect these units to be an issue when we have double precision, regardless of solver type.  I'm not trying to be a jerk, here, and I've definitely run into the problem with MOOSE, which I resolve by nondimensionalization/redimensionalization.  I think this is a great example of the occasional collision between physical scientists and computer scientists.  I hope that clarifies my perspective a bit.
