### ISSUE TITLE
Mesh_modifier tests should be removed

### ISSUE THREAD

**Issue by socratesgorilla** [idaholab/moose#22267] opened 2022-09-29 19:03 UTC
## Reason
The mesh_modifier systems have been removed from MOOSE, yet their tests still remain. These tests are almost all duplicates and have no reason to be there, and for those that aren't, they should be moved to a proper directory.

## Design
Remove mesh_modifiers tests and relocate tests that lower coverage

## Impact
Faster test suite, etc

**Comment by GiudGiud** [comment] 2022-10-12 19:31
Closing as duplicate of https://github.com/idaholab/moose/issues/13814
and addressed by https://github.com/idaholab/moose/pull/20845

**Closed by GiudGiud** 2022-10-12 19:31 UTC
Labels: C: Framework, T: task, C: Meshing
