### ISSUE TITLE
Make ReferenceResidualProblem relative convergence check more robust

### ISSUE THREAD

**Issue by harterj** [idaholab/moose#15475] opened 2020-06-18 18:48 UTC
## Problem Description
Mechanics solve does not converge if we use a convergence criteria of a `nl_rel_tol` with `ReferenceResidualProblem`. To converge mechanics problems I have had to use an absolute tolerance, where I’d prefer to use relative. The `disp_x_ref` variable tracks so close to `disp_x` that we won’t achieve convergence this way. Tagging Alex Lindsay because he’s advised me on this already a bit.

Sample output of the issue

`…`
`22 Nonlinear |R| = 6.376306e-04`
`   Solution, reference convergence variable norms:`
`   disp_x: 0.000554862  disp_x_ref: 0.000554862`
`   disp_y: 0.000314168  disp_y_ref: 0.00032095`
`23 Nonlinear |R| = 4.736822e-04`
`   Solution, reference convergence variable norms:`
`   disp_x: 0.000314396  disp_x_ref: 0.000314873`
`   disp_y: 0.000354302  disp_y_ref: 0.000354376`
`24 Nonlinear |R| = 5.599772e-04`
`   Solution, reference convergence variable norms:`
`   disp_x: 0.000434898  disp_x_ref: 0.000434898`
`   disp_y: 0.000352758  disp_y_ref: 0.000352777`
`25 Nonlinear |R| = 6.412944e-04`
`   Solution, reference convergence variable norms:`
`   disp_x: 0.00035097  disp_x_ref: 0.000356319`
`   disp_y: 0.00053673  disp_y_ref: 0.00053674`
` Solve Did NOT Converge!`
`Aborting as solve did not converge`

## Steps to Reproduce
I have included an input file (and a mesh) which has some notes in the `Executioner` block. If you run the file with and without the various comments, you will see the behavior I am referring to. Without an absolute tolerance specified, when using `ReferenceResidualProblem` on a mechanics problem, the solve just hangs. Playing with the values of this input file (it changes depending on the problem you run), the nonlinear residual of the included simulation input reduces about 12 orders of magnitude from the initial value, so I picked an absolute tolerance which reflects that. The example is in `examples/rel_tol` on my MOOSE branch: https://github.com/harterj/moose/tree/rel_tol_bug

## Impact
This prevents us from using relative convergence criteria for our analysis. It would be extremely helpful if we could get this looked at.

Tag: @vincentlaboure @elementx54 @jortensi @lindsayad

**Comment by lindsayad** [comment] 2020-07-06 17:09
So I've been looking at this, and I don't think this is necessarily a bug. The system is working exactly like I expect it to. The problem is that we don't (currently) have a good reference quantity. We're accumulating into the tag vector from all the volumetric kernels (I believe there's only actually one kernel per element in this problem per variable right? Something like `StressDivergenceTensors`?). The only additional objects we have are the two DirichletBCs which prevent the system from being singular. The problem is that their affect on the residual is quite small on the scale of the kernel residuals. The residual norm at the first nonlinear iteration is 6.01e6. Here is the affect that the DirichletBCs have on the residual:

For dof 21: 2.15e3 -> 0
For dof 102: 2.19e3 -> 0

So the problem is that the reference residual looks almost exactly like the system residual. Because there are other residual entries that are 3 orders of magnitude larger than the residual components being affected by the DirichletBCs, the change exerted by the DirichletBCs is just noise. 

@bwspenc has proposed in the past that we do something like mark the largest magnitude contribution of any kernel as the reference residual quantity and that would work here even though we only have one kernel. We still have the balance of the element-by-element contributions to the residual, e.g. at the centerpoint of the edges we have the LHS element pulling one direction and then the RHS element pulling in the other, so their element residual contributions would have opposite sign.

What do you think @bwspenc ? Time to move on this idea?

**Comment by lindsayad** [comment] 2020-07-06 19:05
I'm wondering about the cleanest way to do this that avoids doing a bunch of checks like `if (tag == reference_vector_tag)` then apply `std::abs`. I'm wondering about the possibility of attaching an arbitrary transform function when the reference `NumericVector` gets constructed that gets applied when doing `NumericVector::add_vector`. The transform I would apply for the reference vector is `std::abs`. I'm curious what @roystgnr thinks of such a design.

**Comment by roystgnr** [comment] 2020-07-07 15:08
The idea of NumericVector::_secret_functor_that_makes_add_not_actually_add horrifies me.  That would be an [IOCCC](https://www.ioccc.org/) worthy design decision.

I would love to be able to do something like expression templates with NumericVector, though.  So instead of calling ```v1 += v2;``` in MOOSE, you'd call ```v1 += abs(v2);```, and instead of allocating a whole new vector like a chump, the ```abs(const NumericVector&)``` overload would return an expression class that would be evaluated entry by entry in ```NumericVector::operator+=(const Expression&)```.  The only catch here is that typically expression templates use *templates*, with non-virtual functions for efficiency, whereas you'd probably want virtual functions so that you could more easily store a base class within MOOSE for generality.

**Comment by lindsayad** [comment] 2020-07-07 15:20
> The idea of NumericVector::_secret_functor_that_makes_add_not_actually_add horrifies me. That would be an [IOCCC](https://www.ioccc.org/) worthy design decision.

Just lol.

> I would love to be able to do something like expression templates with NumericVector, though. So instead of calling `v1 += v2;` in MOOSE, you'd call `v1 += abs(v2);`, and instead of allocating a whole new vector like a chump, the `abs(const NumericVector&)` overload would return an expression class that would be evaluated entry by entry in `NumericVector::operator+=(const Expression&)`. The only catch here is that typically expression templates use _templates_, with non-virtual functions for efficiency, whereas you'd probably want virtual functions so that you could more easily store a base class within MOOSE for generality.

I'm going to look into this. For funsies I actually did implement a transform in `NumericVector` for `add` operations and it works quite smoothly. But I agree with your concerns.

**Comment by lindsayad** [comment] 2020-07-07 15:21
@harterj would it be possible for you to create a `GeneratedMesh(Generator)` version of your mesh so that I can easily coarsen the problem for debugging purposes?

**Comment by lindsayad** [comment] 2020-07-07 15:23
Actually it looks simple enough; I can just do it myself

**Comment by lindsayad** [comment] 2020-07-07 16:34
I actually think that this problem is bullet-proof against any attempt to create a reference residual. You don't even have an inter-element balance here. The balancing happens element-by-element within the the single `StressDivergenceTensors` object which simultaneously combines the thermal expansion/contraction against the material's resistance to deformation. I don't really think there's anything we can do at a framework/libMesh level.

**Comment by bwspenc** [comment] 2020-07-09 20:58
Sorry for being late to chime in.  This is a fairly common issue, and there's no bug here. It's a free expansion problem, so the nodeset that is being used to restrain the model doesn't actually have any reaction loads when it converges, which is why the reference quantity drops along with the residual. Sometimes we'll have problems like this where one of the displacement components behaves like this, but the others don't, and using the grouping option helps. However, you're out of luck here because both disp_x and disp_y behave like this. Currently, the best we can do is use an absolute tolerance as a problem-dependent additional check.

I have an idea that I still think is valid that I've discussed with @lindsayad  before that I'm pretty sure would solve this problem. If we were able to assemble the absolute value of the residual to another tagged vector and compare against that, we could use that as a foolproof reference vector for the convergence check for each variable. It's probably not too hard to hack something in to test this idea out -- I just haven't gotten around to it.

**Comment by bwspenc** [comment] 2020-07-09 21:10
I would add here that there are 3 scenarios where the standard convergence check fails:
1) There is a large scaling difference between the solution variables, so taking the norm of the combined vector skews the convergence check so that it is effectively only checking the variable with larger values.
2) The solution is not changing much from the previous step because the boundary conditions and other aspects of the model aren't changing much over time, so the initial residual is very low because we're already essentially converged at the beginning of the NL iterations.
3) The state of the problem is such that the residual at the DOFs where Dirichlet boundary conditions are applied is essentially zero. This can happen in a free expansion problem like what you had, or in time steps when no loading is applied.

ReferenceResidualProblem addresses the first 2 because it checks the residuals of the variables individually, and compares them against meaningful reference quantities. It struggles with the third one because there's nothing meaningful to compare with, so you have no choice but to provide an absolute tolerance.

I should probably add this to the ReferenceResidualProblem documentation...

**Comment by lindsayad** [comment] 2020-07-09 21:12
@bwspenc the problem with this particular problem is that all the balancing happens within *one* kernel object. There's not even inter-element balancing here. It's all intra-element. Even taking the absolute value of `_local_re` before accumulating into the reference residual has no affect; I've already tried it. Your `_local_re` already has both the effects of thermal expansion and resistance to material deformation summed into it. You would have to apply the absolute value in your stress/strain computation in order for this to work in this case

**Comment by vincentlaboure** [comment] 2020-07-09 21:43
So is the recommendation to set the absolute tolerance to a value much larger than for standard problems, depending on the behavior of the solve?

**Comment by bwspenc** [comment] 2020-07-09 21:51
Here's how I understand what's going on here: You apply a thermal strain, which causes a stress, which results in a nonzero residual and causes the displacements to evolve. After a few iterations, the stress is zero, so the divergence kernel assembles zeroes. I don't really see how it matters that we only have a single kernels, but I do see that my proposed scheme would fail if there were no gradients in the expansion, so the model is completely stress-free...

Anyway, yes, you have to set the absolute tolerance to something nonzero. Usually something like 1e-12 does the trick, but it depends on your model.

**Comment by tophmatthews** [comment] 2020-07-09 21:54
Can't you compare against the TimeDerivative to determine the steady state?

**Comment by bwspenc** [comment] 2020-07-09 21:57
@tophmatthews Do you mean a TimeDerivative kernel? You wouldn't have that for a quasistatic problem.

**Comment by lindsayad** [comment] 2020-07-09 21:59
>  After a few iterations, the stress is zero, so the divergence kernel assembles zeroes.

To me this is the only thing that matters. How do you construct a reference residual when at the point that the problem is truly solved, you only have one object that is providing zeros.

**Comment by tophmatthews** [comment] 2020-07-09 21:59
Yes TimeDerivative kernel. You could do a pseudo-steady state right?

**Comment by bwspenc** [comment] 2020-07-09 22:23
@lindsayad I agree this is a tough situation. I guess the only thing nonzero in a situation like this is the solution variable (displacement), but it's the conjugate to the residual, so it's hard to use it in a convergence check. Sometimes people use energy norms, where they multiply the displacement and residual, but that would be zero too. I'll have to chew on this for a while.

@tophmatthews I'm not quite following what I would do with a TimeDerivative kernel. I don't think we want to require the user to add another kernel, and even if they did, if the solution wasn't changing much, that would still give you zeroes too.

**Comment by bwspenc** [comment] 2020-07-09 22:32
Well, I don't really have a fix for this, but I just submitted a PR that hopefully improves the docuementation.

**Comment by tophmatthews** [comment] 2020-07-09 22:34
Well, in transient simulations where your trying to find the steady state solution for things without BCs (e.g. rate equations), I add the save_in (or whatever you call it now) to the rate equation kernels, and not to the TimeDerivative kernels. That will give the reference to steady state, no? I'm not sure of course.

**Comment by vincentlaboure** [comment] 2020-07-09 22:51
My understanding is that there is no time derivative terms for the mechanics (and that's the physics that really creates the problem we are having - since we run the temperature equation in a separate app)

**Comment by bwspenc** [comment] 2020-07-10 12:58
@tophmatthews Sure, I think what you are doing would work just fine. The whole point of the procedure is to save off some portion of the actual residual and use that as a relative convergence measure that is indicative of the magnitude of the physical response. Usually we save off just the contribution from all the kernels and don't save the contribution of the Dirichlet BCs, but what you are doing would have a similar effect as long as the TimeDerivative kernels have a nonzero contribution. You would start getting zeroes for your reference vector if you hit a case where they don't contribute anything, though, so you'd have to be careful about that.

@vincentlaboure is right about there being no time derivative terms for mechanics. It's not that it would never exist -- we can add inertial forces, which are a time derivative term, but those are only important for dynamic problems. We don't include them for quasistatic analyses because they are negligible. If we included them, they would be close to zero, which wouldn't help us at all for this situation.

**Comment by lindsayad** [comment] 2021-03-08 21:07
I consider this superseded by #17249 . If none of the existing strategies outlined in #17249 would solve the problem proposed here, then we can brainstorm and add the hypothesized solution to #17249

**Closed by lindsayad** 2021-03-08 21:07 UTC
Labels: C: Modules, P: normal
