### ISSUE TITLE
GapHeatTransfer does not work with pre-split distributed mesh

### ISSUE THREAD

**Issue by vincentlaboure** [idaholab/moose#27203] opened 2024-03-27 15:52 UTC
### Bug Description

A segfault is obtained when using `GapHeatTransfer` with a pre-split distributed mesh. If the mesh is not pre-split (or if `GapHeatTransfer` is removed), it works fine.

### Steps to Reproduce

This can be reproduced using the following modified MOOSE test:

```
> module load use.moose moose-apps moose
> cd moose/modules/heat_transfer/test/tests/heat_conduction/2d_quadrature_gap_heat_transfer
> moose-opt -i perfect.i Mesh/uniform_refine=2 --mesh-only     <--- refining just to make sure there are enough elements to distribute
> moose-opt -i perfect.i Mesh/file=perfect_in.e --split-mesh 2
> mpiexec -n 2 moose-opt -i perfect.i Mesh/file=perfect_in.e Mesh/parallel_type=distributed Mesh/use_split=true

Framework Information:
MOOSE Version:           git commit cd68a12857 on 2024-03-14
LibMesh Version:         4e661a5ff0a35eaf798a2817c818d10c5fe6c59c
PETSc Version:           3.20.3
SLEPc Version:           3.20.1
Current Time:            Wed Mar 27 07:36:49 2024
Executable Timestamp:    Fri Mar 15 00:34:49 2024

Parallelism:
  Num Processors:          2
  Num Threads:             1
Mesh: 
  Parallel Type:           distributed (pre-split)
  Mesh Dimension:          2
  Spatial Dimension:       2
  Nodes:                   
    Total:                 162
    Local:                 81
    Min/Max/Avg:           81/81/81
  Elems:                   
    Total:                 128
    Local:                 64
    Min/Max/Avg:           64/64/64
  Num Subdomains:          2
  Num Partitions:          1
  Partitioner:             parmetis
Nonlinear System:
  Num DOFs:                162
  Num Local DOFs:          81
  Variables:               "temp" 
  Finite Element Types:    "LAGRANGE" 
  Approximation Orders:    "FIRST" 
Auxiliary System:
  Num DOFs:                256
  Num Local DOFs:          128
  Variables:               { "qpoint_penetration" "paired_temp" } 
  Finite Element Types:    "MONOMIAL" 
  Approximation Orders:    "CONSTANT" 
Execution Information:
  Executioner:             Steady
  Solver Mode:             Preconditioned JFNK
===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   PID 2396 RUNNING AT sawtooth2
=   EXIT CODE: 139
=   CLEANING UP REMAINING PROCESSES
=   YOU CAN IGNORE THE BELOW CLEANUP MESSAGES
===================================================================================
YOUR APPLICATION TERMINATED WITH THE EXIT STRING: Segmentation fault (signal 11)
```

The error is the same without the uniform refinement step.
If `ThermalContact/active=''` is added or a non pre-split distributed mesh is used, it works as expected.

### Impact

Inability to use pre-split distributed meshes with `GapHeatTransfer` . For large problems, this is a major inconvenience.

**Comment by lindsayad** [comment] 2024-03-27 18:03
this is a specific case of https://github.com/idaholab/moose/issues/25621

**Comment by lindsayad** [comment] 2024-03-27 18:31
As @joshuahansel helped bring to light, this may not actually be a specific case of #25621 since this is using geometric search which does not use the relationship manager system

**Comment by sallustius** [comment] 2024-05-10 23:16
@lindsayad, is there an expected timeline to solve this issue? I am hitting the same error in the context of my NEAMS M2 milestone, and it is preventing me from running a full-core coupled simulation unless I use a huge number of nodes on Sawtooth. I can find a work-around by changing the modeling approach, but it may impact the fidelity of my model.

**Comment by lindsayad** [comment] 2024-05-13 16:12
I've bumped it to the front of the queue for our technical area support project. In our NEAMS multiphysics MOOSE meeting tomorrow I will make sure we can assign a resource to it

**Comment by sallustius** [comment] 2024-05-13 16:15
Thank you, @lindsayad!

**Comment by vincentlaboure** [comment] 2024-05-13 16:17
Yes, thank you!

**Comment by oanaoana** [comment] 2024-05-13 18:04
How time sensitive is this? When is the M2 milestone?

**Comment by sallustius** [comment] 2024-05-13 18:17
@oanaoana, I need to wrap up my simulations by July 10. 
This means I would need this to be fixed by June 10th to be sure I can deliver. If it is not possible to do it, I will need to find a work-around.

**Comment by oanaoana** [comment] 2024-05-13 18:40
@sallustius letting you know once I catch up with Alex, can't assess as is how involved it may be.

**Comment by vincentlaboure** [comment] 2024-05-13 18:56
@oanaoana It is also pretty time sensitive for us. Stefano's timeline would be great. Thank you looking into it!

**Comment by oanaoana** [comment] 2024-05-14 18:13
@sallustius reproducing this and looking through other tests in this module and I guess you should set a `paired_boundary` somewhere, shouldn't you?

**Comment by vincentlaboure** [comment] 2024-05-14 20:40
> @sallustius reproducing this and looking through other tests in this module and I guess you should set a `paired_boundary` somewhere, shouldn't you? Or should it be deduced from ThermalContact? Not sure who to pair to in your example.

Doesn't the `ThermalContactAction` set the `paired_boundary`? At least, I have never seen a `GapHeatTransfer` explicitly set that parameter.

**Comment by lindsayad** [comment] 2024-05-14 21:35
Yes, `secondary` from the `ThermalContact` block becomes `boundary` in the actual bc and `primary` becomes `paired_boundary`

**Comment by oanaoana** [comment] 2024-05-14 21:49
Ok, this makes sense @lindsayad . I did pair them `secondary` and `primary` as per the user file, but then I saw the param `paired` and got me worried I'm missing some essential. Sorry @vincentlaboure  there was a naming override at our end, `paired` is just a good name for many things.

**Comment by oanaoana** [comment] 2024-06-05 14:31
@sallustius Wondering about how you loaded the split mesh above. I pretty much followed your steps and even with a relationship manager the error was the same, up to when I read this https://mooseframework.inl.gov/syntax/Mesh/splitting.html and changed the read.  If you didn't try I kinda wanna go back after I finish testing and see what happens if you read the `.cpr` file with a `FileMeshGenerator` but no relationship manager.

**Comment by vincentlaboure** [comment] 2024-06-05 15:41
> @sallustius Wondering about how you loaded the split mesh above. I pretty much followed your steps and even with a relationship manager the error was the same, up to when I read this https://mooseframework.inl.gov/syntax/Mesh/splitting.html and changed the read. If you didn't try I kinda wanna go back after I finish testing and see what happens if you read the `.cpr` file with a `FileMeshGenerator` but no relationship manager.

I am not sure to understand what you mean by "no relationship manager". Regarding how the split mesh above is loaded, are you asking for something more than the commands mentioned above and repeated below👇?  

```
> moose-opt -i perfect.i Mesh/file=perfect_in.e --split-mesh 2
> mpiexec -n 2 moose-opt -i perfect.i Mesh/file=perfect_in.e Mesh/parallel_type=distributed Mesh/use_split=true
```

**Comment by sallustius** [comment] 2024-06-05 15:46
@oanaoana, this is an example of how we load the split mesh (this problem has displacement as well, but the error can be reproduced in absence of disp):
```
[Mesh]
  [transport_mesh]
    type = FileMeshGenerator
    file = '../mesh/core_mesh_cold.e'
    exodus_extra_element_integers = 'material_id'
   []
   [cmfd_mesh]
     type = FileMeshGenerator
     file = '../mesh/core_mesh_3D_cmfd_cyl_tri.e'
   []
  [mesh]
    type = CoarseMeshExtraElementIDGenerator
    input = transport_mesh
    coarse_mesh = cmfd_mesh
    extra_element_id_name = coarse_element_id
  []
   use_split = true
   split_file = '../mesh/abtr.cpr'
   displacements = 'disp_x disp_y disp_z'
[]```

**Comment by oanaoana** [comment] 2024-06-05 16:06
@vincentlaboure there's something funky with `--use-split` as in it skips the Mesh block and as such some of the "generating" steps. The relationship manager was what we had to add to ghost boundaries properly and assure the split mesh can be read in parallel, but turns out there is a pending issue at the mesh reading level. I get back to you, it might be you need to read it using `FileMeshGenerator` and `--distributed-mesh` and skip `use_split`. Still fiddling around to understand better myself. And thanks @sallustius it looks like your input is almost there, hoping you can soon use this.

**Comment by dschwen** [comment] 2024-06-05 16:15
Can't we deprecate `GapHeatTransfer` in favor of `ModularGapConductanceConstraint`?

**Comment by lindsayad** [comment] 2024-06-05 16:29
That's mostly up to the users @dschwen. I don't know how much people are trying the newer systems, and if they are whether they are sufficiently meeting their needs

**Comment by vincentlaboure** [comment] 2024-06-05 17:03
@dschwen What is the fundamental difference between the 2? Has anyone done a detailed comparison in terms of memory usage, speed and accuracy?

**Comment by dschwen** [comment] 2024-06-05 19:48
The new system is mortar based and has a modular design permitting the user to mix and match arbitrary heat flux models. The old system is an odd Franken-System patched together from boundary conditions, auxkernels, dirac kernels and materials (is that right?).

**Comment by lindsayad** [comment] 2024-06-05 20:15
Maybe not Dirac kernels, but I think you're right about the other systems. It's definitely not grounded in anything mathematical AFAIK like mortar is. @bwspenc is thermal contact based off anything? The traditional mechanical contact system is definitely known in the literature (node-face, node-to-segment). But yea like @dschwen said I'm not sure what thermal contact is really doing

**Comment by joshuahansel** [comment] 2024-06-05 22:06
Should `ModularGapConductanceConstraint` work with a pre-split distributed mesh?

**Comment by joshuahansel** [comment] 2024-06-05 22:20
> Has anyone done a detailed comparison in terms of memory usage, speed and accuracy?

I highly doubt it. Wanna make the first data point, using your problem (without pre-splitting the mesh)? 😉

**Comment by vincentlaboure** [comment] 2024-06-06 12:26
I might be able to take a look at both at some point but, in addition to knowing if `ModularGapConductanceConstraint` works with a pre-split distributed mesh, I would also be interested to understand if it requires AD. Our current problem is a big thermal-only problem so the Jacobian is already exact. I thought that AD didn't do so well for large problems without increasing the container size (but please correct me if I'm wrong).

**Comment by dschwen** [comment] 2024-06-06 12:32
Mortar needs AD to get the derivatives across the gap right. But that doesn't mean you need AD for the entire problem. Only the constraint need it (only on the interface). The AD container size is related to the number of DOFs a derivative needs to be taken w.r.t. This is usually not a function of the mesh size, but if the number of variables that are coupled.

**Comment by vincentlaboure** [comment] 2024-06-06 12:40
Great, thanks for the clarification @dschwen !

**Comment by vincentlaboure** [comment] 2024-06-06 13:58
Good to know @lindsayad. In your experience, what Jacobien contribution did these models typically miss?
My claim was mainly based on the fact that we are using NEWTON and that the convergence is good (in my mind, an imperfect Jacobian would guarantee problems with NEWTON) but let me know if that's not the case.

**Comment by sallustius** [comment] 2024-06-06 14:45
I can try it with my MARVEL model early next week. I'll see what `ModularGapConductanceConstraint ` does.

**Comment by oanaoana** [comment] 2024-06-06 21:06
@sallustius and @vincentlaboure so I pushed a draft PR with an example case `perfect_split.i` that should read meshes in parallel as split in your case. There are now  some issues with the original file "recover" and an internal app, that l have to dig into asap. But hopefully with the current setup you can read meshes in parallel and meet your deadline, if I don't sort out the details by end of this week.

**Comment by vincentlaboure** [comment] 2024-06-06 21:28
Great, thanks a lot @oanaoana! I will try it out next week and report back.

**Comment by vincentlaboure** [comment] 2024-06-10 15:20
So I tried your branch, @oanaoana, and I am still getting the segmentation fault with the example described in the issue description. If I use your `perfect_split.i`, it does not error out but it does not seem to be using *pre-split*:

```
$ mpiexec -n 2 ../../../../heat_transfer-opt -i perfect_split.i 
Framework Information:
MOOSE Version:           git commit 42180d0d85 on 2024-05-31
LibMesh Version:         1c5369aa05eaae8ebeb7930845fce3b1d59cbb37
PETSc Version:           3.20.3
SLEPc Version:           3.20.1
Current Time:            Mon Jun 10 09:16:56 2024
Executable Timestamp:    Mon Jun 10 09:05:15 2024
Parallelism:
  Num Processors:          2
  Num Threads:             1
Mesh: 
  Parallel Type:           distributed
  Mesh Dimension:          2
  Spatial Dimension:       2
```

(the segfaulting runs show `Parallel Type: distributed (pre-split)`)

Are you using a different command?

**Comment by oanaoana** [comment] 2024-06-10 15:50
@vincentlaboure I am not sure I understand what you mean by not using pre-split. It should use the `.cpr` files that should be generated with `mesh-split` as before. I am not sure what the segfault refers to exactly, but there were more changes on the branch to assure the mesh is correctly loaded and the ghosting of points properly performed. I am on it now, and trying to find you off git, to not clutter this if it requires more back and forth.

**Comment by lindsayad** [comment] 2024-06-10 15:52
Talking through the issue on the issue isn't clutter 😄 But you guys do you!

**Comment by oanaoana** [comment] 2024-06-10 15:53
Well the test passed civet already as you can see. There are some loose ends I shall fix now, but not on that particular file.

**Comment by vincentlaboure** [comment] 2024-06-10 17:04
As discussed with @oanaoana, the proposed test already passes with the current version of MOOSE (without her changes) so a better test should be conceived to be fully convincing. Ideally such a test would show a memory spike during mesh initialization before the change but not after.

**Comment by oanaoana** [comment] 2024-06-10 17:10
Also, as per the discussion with @vincentlaboure, what the current `perfect_split.i` checks is if the output of a computation on a distributed mesh is identical to that on a replicated one. There may be two aspects baked into this issue, one is the computation and one is the loading. For the loading the steps should have been from the beginning 

1.` ./heat_transfer-opt -i test/tests/heat_conduction/2d_quadrature_gap_heat_transfer/perfect.i Mesh/file=perfect_in.e --split-mesh 2`
2. `mpiexec -n 2 ./heat_transfer-opt -i test/tests/heat_conduction/2d_quadrature_gap_heat_transfer/perfect.i Mesh/fmg/type=FileMeshGenerator Mesh/fmg/file='perfect_in.cpr' Mesh/parallel_type=distributed`

I add all this to the documentation anyway

**Comment by lindsayad** [comment] 2024-06-12 19:28
> a better test should be conceived to be fully convincing

Convincing of what? From what I understand, this issue (the one in the original post) is solvable with current MOOSE by not using `--use-split`, but instead using `FileMeshGenerator` to load the split mesh. Is that correct?

**Comment by oanaoana** [comment] 2024-06-12 19:29
@lindsayad  Yes, that is correct!

**Comment by lindsayad** [comment] 2024-06-12 19:36
Should we be deleting the `--use-split` option if it has potential outcomes like segmentation faults? Is there any reason why using a `FileMeshGenerator` any time you want to use a previously split mesh is a no-go? @vincentlaboure @sallustius

**Comment by sallustius** [comment] 2024-06-12 19:53
@oanaoana, so the only think we have to do is to load the split mesh directly with the mesh generator? @lindsayad, I would delete --use-split if it doesn't have any use and can be the cause of seg-faults.

```
[Mesh]
  [./fmg]
    type = FileMeshGenerator
    file = 'perfect_in.cpr'
  [../]
  parallel_type = distributed
[]

```

**Comment by oanaoana** [comment] 2024-06-12 20:11
@sallustius that is correct! And if you have other problems this PR takes the extra step to ensure proper ghosting and it will be soon merged.

**Comment by sallustius** [comment] 2024-06-12 20:24
Understood. We should remove the --use-split option then. Should this page be updates as well then?
https://mooseframework.inl.gov/syntax/Mesh/splitting.html. It talks about employing --use-split and resorting to the MeshGenerator only if you need to perform further meshing operations. However, in this case, we obtain a seg-fault even if we don't perform any additional meshing.

**Comment by lindsayad** [comment] 2024-06-12 20:28
I will leave it up to @oanaoana whether she wants to do that in her ghosting PR or save it for a follow-up

**Comment by loganharbour** [comment] 2024-06-12 20:31
I have a strong inclination to keep it, even though it's a huge pain as we see. It's also difficult for the user, but I think there are cases when it's really needed. 

We could employ the test harness to do split testing as we do with recover testing.

**Comment by oanaoana** [comment] 2024-06-12 20:35
@loganharbour I kept it for now! I was thinking to just extend the warning on the page, that users who use it successfully may still do so but keep aware skipping the Mesh block may have deeper implications. I think this could still be agreed upon but is maybe not so urgent.

**Comment by sallustius** [comment] 2024-06-12 20:37
@loganharbour, can you provide an example in which --use-split is needed in lieu of using the FileMeshGenerator?

**Comment by lindsayad** [comment] 2024-06-12 20:39
If we keep it, we need to make sure that a user never gets a segmentation fault for "normal" use like for @vincentlaboure and @sallustius, e.g. we should know what causes problems and issue an error up front telling the user `--use-split` is not viable for them. Having seg faults ever, but especially when there is an alternative that works, is not something we want to persist

**Comment by oanaoana** [comment] 2024-06-12 20:45
I strongly suspect that the seg fault could be avoided if one adds an action, such that the distribution is picked up earlier. But this requires a bit more digging, for example is this an issue only for `GapHeatTransfer` and an action is needed only for this module, or should one make sure `--use-split` kicks in after reading the Mesh block, and does one even need both `split` and `distributed`?

**Comment by vincentlaboure** [comment] 2024-06-12 20:46
When I said I wasn't fully convinced, it's because when we use `file = 'perfect_in.cpr'`, the screen shows `Parallel Type: distributed` as opposed to `Parallel Type: distributed (pre-split)`, which made me think that it wasn't really using pre-split. But I guess, if it is obvious to all the MOOSE developers that using the .cpr file implies that each proc only sees its partition + the needed ghost elements, then it's all good 👍

**Comment by oanaoana** [comment] 2024-06-12 21:12
@vincentlaboure I am with you on this! It is part of the messaging of `split`, as we discussed the other day, and it is deceiving. But as this thread indicates some assessment of how to handle `split` in general is in order.

**Comment by lindsayad** [comment] 2024-06-12 21:49
> But I guess, if it is obvious to all the MOOSE developers that using the .cpr file implies that each proc only sees its partition + the needed ghost elements, then it's all good

Yea, when we split the mesh and write to checkpoint we only write the elements local to the split plus the elements we get through querying ghosting functors

**Comment by vincentlaboure** [comment] 2024-06-13 11:50
> > But I guess, if it is obvious to all the MOOSE developers that using the .cpr file implies that each proc only sees its partition + the needed ghost elements, then it's all good
> 
> Yea, when we split the mesh and write to checkpoint we only write the elements local to the split plus the elements we get through querying ghosting functors

Excellent, that's great news!

**Comment by GiudGiud** [comment] 2024-09-06 19:32
Closing this, solution was to use the FileMeshGenerator instead of --use-split. These ghosting issues not tied to GapHeatTransfer and any object with similar requirements  would hit it, until we remove --use-split

**Closed by GiudGiud** 2024-09-06 19:32 UTC
Labels: C: Framework, T: defect, P: normal
