### ISSUE TITLE
Robustify reinitElemPhys and reinitNeighborPhys behavior

### ISSUE THREAD

**Issue by jiangwen84** [idaholab/moose#10823] opened 2018-02-19 22:37 UTC
## Rationale

In ``FEProblemBase``, ``reinitNeighborPhys`` is used to reinit the shape functions at physical points. It will also reinit on the ``_displaced_problem`` when the ``_displaced_problem`` != NULL). This condition is NOT sufficient. If the kernel/bc/constraint only runs on the undisplaced_mesh (use_displaced_mesh = false), it should not let _displaced_problem to reinit shape functions. 
    
## Description

We need to add _reinit_displaced_face and _reinit_displaced_elem to the if-statement. 

## Impact

Bug fixed. This function might be used mainly by X-FEM and the change should not affect other staffs.

**Comment by lindsayad** [comment] 2021-03-17 20:28
We have users coming out of the woodwork (@tophmatthews @bwspenc @hugary1995) complaining about failed `FEInterface::inverse_map` calls due to the logic in `FEProblemBase::reinitElemPhys` and `FEProblemBase::reinitNeighborPhys`. This is because these methods will call for physical point inversions for the ***exact same physical points*** on both undisplaced and displaced meshes. This seems terrible. You can easily imagine scenarios in which you call those reinit methods with points that may lie only on the undisplaced mesh. I propose that we stop calling the displaced problem `reinit*Phys` from `FEProblemBase::reinit*Phys`and if the user really does want both undisplaced and displaced reinits, then they explicitly ask for them.

**Comment by hugary1995** [comment] 2021-03-19 02:48
I have a relatively simple 25-element regression test: [https://github.com/hugary1995/moose/blob/geometriccut_multimaterial/modules/xfem/test/tests/moving_interface/moving_bimaterial_finite_strain.i](https://github.com/hugary1995/moose/blob/geometriccut_multimaterial/modules/xfem/test/tests/moving_interface/moving_bimaterial_finite_strain.i) that sometimes produces different results (it results in exodiff once every 10 runs or so). It is a relatively simple input file with only large deformation mechanics and xfem. The only "dangerous" piece there is the `XFEMSingleVariableConstraint` which derives from `ElemElemConstraint`.

Interestingly, if I set `use_displaced_mesh = false`  in the Mesh block, it produces consistent results from runs to runs. I am not entirely sure that this is related to the `reinitNeighborPhys` issue, but I will give it a try once the `reinitNeighborPhys` is fixed.

Just leaving this message here to remind myself.

**Comment by lindsayad** [comment] 2021-05-18 21:05
Closed by #17355

**Closed by lindsayad** 2021-05-18 21:05 UTC
Labels: C: MOOSE, P: normal, T: defect
