### ISSUE TITLE
Add TricrystalTripleJunctionIC initial condition to phase-field module

### ISSUE THREAD

**Issue by jarinfrench** [idaholab/moose#7196] opened 2016-06-16 17:27 UTC
### Description of the enhancement or error report
This ic allows the user to specify two angles in degrees to simulate three grains meeting at a triple junction.

### Rationale for the enhancement or information for reproducing the error
The ability to simulate a single triple junction is helpful to analyze directly what is happening at a triple junction.  Also takes a step forward to testing the model implemented in MOOSE for anisotropic grain growth.

### Identified impact
(i.e. Internal object changes, limited interface changes, public API change, or a list of specific applications impacted)

**Comment by dschwen** [comment] 2016-06-16 17:55
Which boundary condition is this to be used with?

**Comment by jarinfrench** [comment] 2016-06-16 18:01
I've used this without a BC block at all, but I've also used Neumann bcs.

**Comment by jarinfrench** [comment] 2016-06-16 20:25
Any ideas why a test would fail when I run it in parallel versus succeeding when I run it in series?

**Comment by permcody** [comment] 2016-06-16 20:35
The list is big, where would you like to start?

Are we talking Exodiff, or are we talking crash? If it's a diff, how big?
This last case is fairly common and can usually be resolved by converging
your solution tighter.

Cody

**Comment by jarinfrench** [comment] 2016-06-16 20:38
It's an Exodiff test, and the difference is:
```
Nodal variables:
gr0   rel diff: -4.7735351e-10 ~ -4.7731072e-10 = 8.96538e-05 (node 1843)
gr1   rel diff: -4.4328462e-10 ~ -4.4277972e-10 = 1.13901e-03 (node 6201)
gr2   rel diff: -2.9037049e-10 ~ -2.9053556e-10 = 5.68144e-04 (node 1534)
```
But I don't quite know what that tells me.

**Comment by permcody** [comment] 2016-06-16 20:50
You are seeing a raw solution value (doesn't really matter if it's at a
node, or element). The first value is the one from the gold file, the
second from the test you just ran. The final number is the relative
difference.

Those values are essentially zero (-2.9e-10). The problem is that since
they are really close to zero, it doesn't take much to make the relative
difference look rather big. So in this case you are falling just outside of
the two normal tolerance checks (relative difference 5.5e-6 or absolute
zero 1e-10). I might recommend that you set your abs zero just a little bit
higher in your "tests" file (1e-10 -> 1e-9) and try again.

To see the list of parameters you can set in a "tests" file, just run
"./run_tests --dump".

Cody

**Comment by jarinfrench** [comment] 2016-06-17 13:34
I fiddled around with the abs_zero tolerance, and the test only passes when I set abs_zero to 1e-5, which doesn't seem quite right to me.  Should I have my abs zero tolerance that high, or should I be looking somewhere else?

**Comment by permcody** [comment] 2016-06-20 14:41
1e-5 isn't very tight so you have to ask yourself why is this happening? Is
your test not very well designed? How does your convergence look? Do you
have one or more variables that aren't converging tightly while the others
are? Are you using screwy nonlinear tolerances either relative or absolute?

With a test this loose it's likely to diff as you move from platform to
platform.

**Closed** 2016-07-12 19:13 UTC
Labels: C: Modules, P: normal, T: task
