### ISSUE TITLE
Unable to edit input files sometimes when I switch input files

### ISSUE THREAD

**Issue by permcody** [idaholab/moose#8811] opened 2017-03-26 01:18 UTC
### Description of the enhancement or error report

It looks like there may be a problem with the input file tab when switching input files. See the notes below for how I can reproduce.

### Rationale for the enhancement or information for reproducing the error

I'm bouncing back and forth between `phase_field/examples` and `phase_field/tests`. It appears to read the input files and I can execute them but I can't seem to edit them. Nothing opens when I double click on it in the InputFile tab.

### Identified impact
(i.e. Internal object changes, limited interface changes, public API change, or a list of specific applications impacted)

Medium: Peacock usability

**Comment by brianmoose** [comment] 2017-03-27 17:22
Here was what I could reproduce which could be what you are seeing.
Open the first input file. Start editing a block. With that block editing window still open, switch to another input file. In the process of switching to another input file, the main peacock window came to the front and the block editing window went to the back, out of sight. Any attempt at editing the blocks on the new input file fail because the block editing window is still open. Closing the block editor window allows editing of blocks on the new input file.

I need to get rid of the existing block editor window when switching input files. I think it is probably also a good idea to raise it when you click on the tree, just in case it got hidden by other windows.

**Comment by permcody** [comment] 2017-03-27 23:47
That may be it. I'll let you know if this fixes it.

**Closed** 2017-03-27 23:48 UTC
Labels: C: Peacock, P: normal, T: defect
