### ISSUE TITLE
Possible issue with calculating Flux with displacements

### ISSUE THREAD

**Issue by permcody** [idaholab/moose#6526] opened 2016-03-08 19:50 UTC
### Description of the enhancement or error report

We have a user reporting an unexpected result of a flux calculation when using displaced mesh with a navier stokes simulation.

### Rationale for the enhancement or information for reproducing the error

Problem was found using the navier stokes module and can be reproduced with the input file attached in the following discussion:
https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/moose-users/O14Y3ibw5Ro/58tWm-fwBAAJ

### Identified impact
(i.e. Internal object changes, limited interface changes, public API change, or a list of specific applications impacted)

Calculations on displaced mesh could be compromised.

**Comment by friedmud** [comment] 2016-03-08 23:50
I don't think it's a problem calculating the flux.  He is actually getting the wrong/different answer using displaced mesh vs a similar grid he displaced in Cubit.

**Comment by jwpeterson** [comment] 2016-03-14 22:24
This turned out to be caused by trying to use FIRST-order displacement variables on a mesh with SECOND-order elements.  This just doesn't work, so we added a test to make sure this situation is detected.

Fixed by da4719e.

**Closed by jwpeterson** 2016-03-14 22:24 UTC
Labels: C: Modules, P: critical, T: defect
