### ISSUE TITLE
Convergence Issues

### ISSUE THREAD

**Issue by edwardXZ06** [idaholab/moose#18501] opened 2021-08-03 02:05 UTC
I have used current UMAT interface to run a bug free simple hyperelastic umat file, yet the convergence perform really bad no matter I use Newton or PJFNK.
Does this mean for the nonlinear problem, we shall specify the Jacobian ourselves, considering this interface has not been built to work with the AD?

_Originally posted by @dschwen in https://github.com/idaholab/moose/issues/14974#issuecomment-828758486_

**Comment by dschwen** [comment] 2021-08-03 02:11
Duplicate of #18500

**Closed by dschwen** 2021-08-03 02:11 UTC

**Comment by dschwen** [comment] 2021-08-03 17:53
Side note, this was a bug in our UMAT interface after all: https://github.com/idaholab/moose/issues/18516
