### ISSUE TITLE
Functional expansion tools module unit test failures

### ISSUE THREAD

**Issue by brianmoose** [idaholab/moose#10848] opened 2018-02-21 18:21 UTC
## Rationale

There are unit tests under `modules/functional_expansion_tools/unit` that are not currently getting
tested. It would be nice to add them but they currently don't work.

## Description

Compiling fails:
```
modules/functional_expansion_tools/unit/src/Cartesian.C:25:27: error: implicit instantiation of undefined template 'std::__1::array<double, 15>'
  std::array<Real, order> truth = {{0.50000000000000,
                          ^
/opt/moose/llvm-5.0.1/include/c++/v1/__tuple:223:92: note: template is declared here
template <class _Tp, size_t _Size> struct __attribute__ ((__type_visibility__("default"))) array;
```
This is easily fixed by `#include <array>` but then there are 4 failed unit tests:
```
[  FAILED  ] FunctionalExpansionsTest.hashPoint
[  FAILED  ] FunctionalExpansionsTest.hashPointAndTime
[  FAILED  ] FunctionalExpansionsTest.hashRealVector
[  FAILED  ] FunctionalExpansionsTest.hashVararg
```

## Impact

More testing

**Comment by brianmoose** [comment] 2018-02-22 14:08
@BruceWyxv

**Comment by BruceWyxv** [comment] 2018-02-22 17:07
I can be assigned this issue.

What was the cause of the failure? Is there more information for the failure? Last I checked these compiled and ran fine on my platform.

**Comment by brianmoose** [comment] 2018-02-22 17:15
```
[ RUN      ] FunctionalExpansionsTest.hashPoint
/Users/algebk-mac/projects/moose2/modules/functional_expansion_tools/unit/src/Hashing.C:19: Failure
      Expected: hashing::hashCombine(location)
      Which is: 1019266789126350417
To be equal to: truth
      Which is: 12573501117625172216
[  FAILED  ] FunctionalExpansionsTest.hashPoint (1 ms)
[ RUN      ] FunctionalExpansionsTest.hashPointAndTime
/Users/algebk-mac/projects/moose2/modules/functional_expansion_tools/unit/src/Hashing.C:28: Failure
      Expected: hashing::hashCombine(time, location)
      Which is: 9858897897724420476
To be equal to: truth
      Which is: 5131894250494321433
[  FAILED  ] FunctionalExpansionsTest.hashPointAndTime (0 ms)
[ RUN      ] FunctionalExpansionsTest.hashIntVector
[       OK ] FunctionalExpansionsTest.hashIntVector (0 ms)
[ RUN      ] FunctionalExpansionsTest.hashRealVector
/Users/algebk-mac/projects/moose2/modules/functional_expansion_tools/unit/src/Hashing.C:57: Failure
      Expected: hashing::hashLargeContainer(vector)
      Which is: 14012783808619111608
To be equal to: truth
      Which is: 17839983326257054046
[  FAILED  ] FunctionalExpansionsTest.hashRealVector (0 ms)
[ RUN      ] FunctionalExpansionsTest.hashVararg
/Users/algebk-mac/projects/moose2/modules/functional_expansion_tools/unit/src/Hashing.C:117: Failure
      Expected: value
      Which is: 5562256127537298136
To be equal to: truth
      Which is: 11318853036716890990
[  FAILED  ] FunctionalExpansionsTest.hashVararg (0 ms)

**Closed** 2018-02-22 22:36 UTC
