### ISSUE TITLE
deprecate declarePropertyOld, declarePropertyOlder, initQpStatefulProperties

### ISSUE THREAD

**Issue by rwcarlsen** [idaholab/moose#8339] opened 2017-01-17 23:15 UTC
#8278 changed properties to be auto-promoted to stateful whenever their old/older versions are retrieved anywhere.  Now declarePropertyOld, declarePropertyOlder are no longer necessary and need to be deprecated.

It also became clear that property initialization (i.e. ``initQpStatefulProperties``) should happen for all properties - not just stateful ones and should generally always be implemented by all material classes.  So we want to deprecate ``initQpStatefulProperties`` and create ``initQpProperties`` to replace it.

See discussion in #8278 for more details.

**Comment by YaqiWang** [comment] 2017-01-17 23:27
This design is wrong. It forces users to implement `initQpProperties`, which makes no sense to materials only depending on the current state.

**Comment by rwcarlsen** [comment] 2017-01-17 23:32
@YaqiWang - they are not forced to implement it.  It is only required to be implemented in materials if/when code somewhere tries to retrieve an Old/Older value of a property owned/declared by that material.

**Comment by YaqiWang** [comment] 2017-01-17 23:56
This abuse stateful material properties. It causes a consequence of more memory consumption. Stateful material property should by definition be a property depending on its old states. On the other hand, I do know why this issue comes up. Automatic promotion should be done in my proposed way and whenever it happens, moose should issue a warning. In summary, stateful should by design but not by consumer. `initQpStatefulProperties` is called twice in `FEProblemBase::initialSetup` currently, which should be marked as one of legacies.

**Comment by friedmud** [comment] 2017-01-18 00:39
@YaqiWang the proper place to complain about automatic promotion is here: https://github.com/idaholab/moose/pull/8278

I'll reply to your comment over there (to keep the discussion there)

**Closed** 2017-07-13 17:56 UTC
Labels: C: MOOSE, P: normal, T: task
