### ISSUE TITLE
DerivativeParsedMaterial start-up performance issues

### ISSUE THREAD

**Issue by dschwen** [idaholab/moose#13570] opened 2019-06-13 16:23 UTC
## Bug Description
 I have identified two bottle necks in the startup (differentiation phase) if DerivativeParsedMaterials. One takes 26.6% of the entire derivation time, and one takes 68.3%. Both involve an unnecessary amount of string operations that I may be able to trim
down considerably.

## Steps to Reproduce
Run a simulation with DerivativeParsedMaterials that use lots of material properties that are provided by DerivativeParsedMaterials themselves (chain rule).

## Impact
Performance improvement.

**Comment by permcody** [comment] 2019-06-13 16:46
Is this really a bug? We really need to be careful about bugs that are really enhancements. These are going to bite us when we deploy under NQA-1.

**Comment by dschwen** [comment] 2019-06-13 17:00
It is a serious design flaw (or combination of multiple flaws, some in FParser). Up to you, I can reclassify as a feature, too...

**Comment by permcody** [comment] 2019-06-13 17:03
The problem is that NQA-1 will require us to document every bug for a production release. It might be really annoying but if it works, it might not be a bug, especially in terms of the scope of the production code. Now this isn't a universal rule. We do have "performance" requirements so if this has an impact on the production code usage, it would be a bug. I just want developers to think about the right classification so it doesn't adversely impact us at release time.  BTW - I'm working on changing the language for the two templates yet again to try to make this idea more clear.

**Comment by dschwen** [comment] 2019-06-13 17:13
How about a new `performance` label (rather than slapping `defect` on this)?

**Comment by dschwen** [comment] 2019-06-13 17:14
And do we have to document bugs that got fixed?!

**Comment by permcody** [comment] 2019-06-13 17:26
The normal issue closing process with tag == bug. I'm hoping that there's not a manual process for that part. The part where there may be a manual process is once the system has gathered open bugs a human might have to go down and classify them as problematic or not.

**Closed** 2019-06-13 21:00 UTC
Labels: C: MOOSE, T: defect, T: task

**Comment by tophmatthews** [comment] 2019-06-13 21:20
What about the other 68.3%? I'm really interested in getting the startup time down for derivative parsed materials for my cluster dynamics simulations
