### ISSUE TITLE
Error running tests

### ISSUE THREAD

**Issue by lyan1** [idaholab/moose#9349] opened 2017-06-20 20:02 UTC
### Description of the enhancement or error report

I followed the instructions in the user guide and the building process went well. When I tried to run the tests with "./run_tests -j8", most of them passed, but two failed, seemingly with the same root cause:

 auxkernels/solution_aux.thread_test.......................................................... FAILED (ERRMSG)
auxkernels/solution_aux.thread_test: Working Directory: /project/lyan1/packages/sources/moose/test/tests/auxkernels/solution_aux
auxkernels/solution_aux.thread_test: Running command: mpiexec -n 1 /project/lyan1/packages/sources/moose/test/moose_test-opt --n-threads=2 -i thread_xda.i --error --no-gdb-backtrace
auxkernels/solution_aux.thread_test: terminate called after throwing an instance of 'std::runtime_error'
auxkernels/solution_aux.thread_test:   what():  pthread_attr_setstacksize: Invalid argument
auxkernels/solution_aux.thread_test: 
auxkernels/solution_aux.thread_test: ===================================================================================
auxkernels/solution_aux.thread_test: =   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
auxkernels/solution_aux.thread_test: =   PID 48873 RUNNING AT qb033
auxkernels/solution_aux.thread_test: =   EXIT CODE: 6
auxkernels/solution_aux.thread_test: =   CLEANING UP REMAINING PROCESSES
auxkernels/solution_aux.thread_test: =   YOU CAN IGNORE THE BELOW CLEANUP MESSAGES
auxkernels/solution_aux.thread_test: ===================================================================================
auxkernels/solution_aux.thread_test: YOUR APPLICATION TERMINATED WITH THE EXIT STRING: Aborted (signal 6)
auxkernels/solution_aux.thread_test: This typically refers to a problem with your application.
auxkernels/solution_aux.thread_test: Please see the FAQ page for debugging suggestions
auxkernels/solution_aux.thread_test: 

restart/kernel_restartable.with_threads...................................................... FAILED (ERRMSG)
restart/kernel_restartable.with_threads: Working Directory: /project/lyan1/packages/sources/moose/test/tests/restart/kernel_restartable
restart/kernel_restartable.with_threads: Running command: mpiexec -n 1 /project/lyan1/packages/sources/moose/test/moose_test-opt --n-threads=4 -i kernel_restartable.i Outputs/restart/file_base=kernel_restartable_out_threads --error --no-gdb-backtrace
restart/kernel_restartable.with_threads: terminate called after throwing an instance of 'std::runtime_error'
restart/kernel_restartable.with_threads:   what():  pthread_attr_setstacksize: Invalid argument
restart/kernel_restartable.with_threads: 
restart/kernel_restartable.with_threads: ===================================================================================
restart/kernel_restartable.with_threads: =   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
restart/kernel_restartable.with_threads: =   PID 49701 RUNNING AT qb033
restart/kernel_restartable.with_threads: =   EXIT CODE: 6
restart/kernel_restartable.with_threads: =   CLEANING UP REMAINING PROCESSES
restart/kernel_restartable.with_threads: =   YOU CAN IGNORE THE BELOW CLEANUP MESSAGES
restart/kernel_restartable.with_threads: ===================================================================================
restart/kernel_restartable.with_threads: YOUR APPLICATION TERMINATED WITH THE EXIT STRING: Aborted (signal 6)
restart/kernel_restartable.with_threads: This typically refers to a problem with your application.
restart/kernel_restartable.with_threads: Please see the FAQ page for debugging suggestions

Then the test process itself crashed with:

vectorpostprocessors/line_function_sampler.test........................................................... OK
vectorpostprocessors/csv_reader.parallel..................................................... [MIN_CPUS=2] OK
Traceback (most recent call last):
  File "./run_tests", line 26, in <module>
    TestHarness.buildAndRun(sys.argv, app_name, MOOSE_DIR)
  File "/project/lyan1/packages/sources/moose/python/TestHarness/TestHarness.py", line 34, in buildAndRun
    harness.findAndRunTests()
  File "/project/lyan1/packages/sources/moose/python/TestHarness/TestHarness.py", line 192, in findAndRunTests
    self.launchTest(find_only, file, dirpath, testers)
  File "/project/lyan1/packages/sources/moose/python/TestHarness/TestHarness.py", line 271, in launchTest
    self.runner.run(tester, command)
  File "/project/lyan1/packages/sources/moose/python/TestHarness/RunParallel.py", line 93, in run
    self.startReadyJobs(slot_check)
  File "/project/lyan1/packages/sources/moose/python/TestHarness/RunParallel.py", line 165, in startReadyJobs
    self.run(tester, command, recurse=False, slot_check=slot_check)
  File "/project/lyan1/packages/sources/moose/python/TestHarness/RunParallel.py", line 126, in run
    tester.prepare(self.options)
  File "/project/lyan1/packages/sources/moose/python/TestHarness/testers/RunException.py", line 32, in prepare
    file_paths.append(self.name() + '.processor.{}'.format(processor_id))
ValueError: zero length field name in format

I'd appreciate it for any insight.

Cheers,
Le

### Rationale for the enhancement or information for reproducing the error

MOOSE: commit 2ca0f72b3c6c7148860ca490b0e6d874098cd23a
OS: RHEL 6.8 (kernel 2.6.32)
Compiler: Intel 16.0.3
Library: PETSc 3.6.4, MVAPICH2 2.3a 
Python: 2.6.6

### Identified impact
(i.e. Internal object changes, limited interface changes, public API change, or a list of specific applications impacted)

**Comment by permcody** [comment] 2017-06-20 20:10
You are better off contacting the mailing list with these kinds of issues. There are actually several problems here that we'll have to work through to get you up and running.  First problem is that we require Python 2.7. We no longer support Python 2.6x. This is why the "./run_tests" script eventually failed with a nasty stack trace. It appears that something is going wrong with threading in general. I can't see all the output, but it appears that the tests that are trying to use threads are just failing. It's difficult to say where the problem is from this output. We've had a few people report problems with threading in the past. It might just be easier to force a different threading model (MOOSE supports 3). The default is Intel's TBB, but you can also use OpenMP, or Pthreads, or you can just turn threading off!

Honestly, not many people use threads routinely. You generally don't need it until you start running thousands of processors. You'll get better scalability with MPI over threading.

**Comment by permcody** [comment] 2017-06-20 20:11
I'm going to close this issue. If my response isn't helpful enough to you, please contact the mailing list where these kinds of support issues can be better handled.

**Closed** 2017-06-20 20:11 UTC
Labels: R: invalid
