### ISSUE TITLE
segment fault with example/ex05_amr

### ISSUE THREAD

**Issue by lw4992** [idaholab/moose#5837] opened 2015-10-20 16:04 UTC
When using example/ex05_amr to test the new adaptivity system on gcc 4.2 with openmpi 1.6.2 , a segment fault occurs, while, everything is OK on gcc 4.8 with openmpi 1.8.4! 
In FEProblem.h, `adaptivity()` was turned off,

```
#ifdef LIBMESH_ENABLE_AMR
  // Adaptivity /////
  Adaptivity & adaptivity() { return _adaptivity; }
  virtual void adaptMesh();
#endif //LIBMESH_ENABLE_AMR
```

however,  `SetAdaptivityOptionsAction::act()` required to call `_problem->adaptivity();`

```
void
SetAdaptivityOptionsAction::act()
{
  Adaptivity & adapt = _problem->adaptivity();

  if (isParamValid("marker"))
    adapt.setMarkerVariableName(getParam<MarkerName>("marker"));
  if (isParamValid("initial_marker"))
    adapt.setInitialMarkerVariableName(getParam<MarkerName>("initial_marker"));

  adapt.setCyclesPerStep(getParam<unsigned int>("cycles_per_step"));

  adapt.setMaxHLevel(getParam<unsigned int>("max_h_level"));

  adapt.init(getParam<unsigned int>("steps"), getParam<unsigned int>("initial_steps"));
  adapt.setUseNewSystem();

  adapt.setTimeActive(getParam<Real>("start_time"), getParam<Real>("stop_time"));
}
```

Is here issue?

**Comment by permcody** [comment] 2015-10-20 16:08
A segfault is different than a logic error which I'm not sure I see here. I suspect the issue is somewhere else. Have you run this through the debugger yet? Segfaults are the easiest errors to track down.

**Comment by lw4992** [comment] 2015-10-25 06:03
example/ex05_amr called `ErrorFractionMarker` as `marker'. The segfault was caused by `addRangeCheckedParam`, which did not work correctly on gcc4.1.2. Maybe, it was  `fparser`'s falut. 
```

template<>
InputParameters validParams<ErrorFractionMarker>()
{
  InputParameters params = validParams<IndicatorMarker>();
  params.addRangeCheckedParam<Real>("coarsen", 0, "coarsen>=0 & coarsen<=1",
                                    "Elements within this percentage of the min error will be coarsened.  Must be between 0 and 1!");
  params.addRangeCheckedParam<Real>("refine", 0, "refine>=0 & refine<=1",
                                    "Elements within this percentage of the max error will be refined.  Must be between 0 and 1!");
  return params;
}
```

**Comment by permcody** [comment] 2015-10-26 14:45
What OS/system are you on?

GCC 4.1.2 is from 2007!. Maybe try updating to a compiler built in this
decade?

**Comment by jwpeterson** [comment] 2015-10-26 15:07
On Mon, Oct 26, 2015 at 8:45 AM, Cody Permann <notifications@github.com>
wrote:

> What OS/system are you on?
>
> GCC 4.1.2 is from 2007!. Maybe try updating to a compiler built in this
> decade?


Sounds like an OSX system GCC from before they switched 100% over to clang.

Both libmesh and MOOSE are known to not work with this compiler and to
produce very weird segfaults, in fact it was one of the reasons we started
building the MOOSE redistributable package....

-- 
John

**Comment by permcody** [comment] 2015-10-29 19:05
@lw4992 - Any luck fixing this? Did you figure out if you are using the old Apple GCC compiler?

**Comment by lw4992** [comment] 2015-10-30 11:02
@permcody - Sorry for my late. I'm using the RedHat Linux on an old cluster, which is same age with MOOSE. :). 
Our new machine is setting up, so, maybe no one will care this issue any more. Mmm....

**Comment by permcody** [comment] 2016-12-06 16:19
We definitely don't support GCC 4.1.2 anymore. I'm closing this ticket unless this can be produced on a modern compiler.

**Closed by permcody** 2016-12-06 16:19 UTC
Labels: C: Examples, P: normal, R: Not Fixed, T: task
