### ISSUE TITLE
"Catastrophic error" in GrainTracker

### ISSUE THREAD

**Issue by dschwen** [idaholab/moose#7122] opened 2016-05-31 21:37 UTC
### Description of the enhancement or error report
A 3D input file (7b038ad) yields 

```
Now Boundaing Boxes Expanded - This is a catastrophic error!
```

### Rationale for the enhancement or information for reproducing the error
Error message is unclear and the error should never occur (internal logic error in GT)

### Identified impact
Prevents certain GT simulations to run.

**Comment by permcody** [comment] 2016-05-31 21:56
Thanks I'll take a look

**Comment by permcody** [comment] 2016-06-20 19:07
@dschwen - I got carried away with "fixing" this semi-local thing and basically rewrote large chunks of the GrainTracker again this weekend: https://github.com/idaholab/moose/pull/7201

I was able to reproduce this problem under some very odd conditions and I believe it is due in part to an implementation error of the algorithm. In short, the bounding boxes weren't taking into account the halo elements which is just bad! This doesn't really explain exactly how this error was occurring but the implementation issue has since been fixed and I haven't been able to reproduce this problem since then:
https://github.com/idaholab/moose/pull/7201

Sadly though, now that the halos are part of the feature, this input file doesn't run for another reason: There simply isn't enough mesh to set up a problem with 100 grains when you only have 1000 elements. Take a look at the 3D problem I added with this PR. It's small enough to run on a workstation and looks reasonable.

**Comment by dschwen** [comment] 2016-06-20 19:26
So... why not 50 grains? Or whatever number works.

**Comment by permcody** [comment] 2016-06-20 19:29
The input file just doesn't work. You have a really narrow interface width that can't be captured by your mesh resolution. I'm not sure you'd be able to do anything with this with even a few grains. To make this input file work you'd need to increase your interface width a lot (effectively zoom in) then lower the number of grains in the simulation so that they are larger than a cell or two.

**Comment by permcody** [comment] 2016-06-20 19:34
Since I've dicked with this so much in the past I think it would be worthwhile to have the capability to set up PF simulations with a given number of grains with a more a less "fixed" width interface. If you said 100 you'd get the right boundary width and domain size to make that work. If you said 5, you'd get the right boundary width and domain size to make that work.

**Comment by permcody** [comment] 2016-07-21 22:16
This error is no longer reproducible, but this input file as it stands doesn't work either. The fundamental problem with this file is that there aren't enough elements to capture the grains and interface. I'm currently working up a better 3D example with adaptivity (already running). I'll get it checked in somewhere when I'm doing fiddling with it.

**Closed by permcody** 2016-07-21 22:16 UTC
Labels: C: Modules, P: normal, T: task
